(() => {
  "use strict";
  const D = window.RoomData;
  const $ = (s, root=document) => root.querySelector(s);
  const $$ = (s, root=document) => [...root.querySelectorAll(s)];
  const app = $("#app");
  const portal = D.portal;
  const state = { page:null, orgId:null, customerId:null, map:null, mapLayers:[], cache:{}, customerTab:"home" };
  const esc = (v) => String(v ?? "").replace(/[&<>'"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
  const fmtMoney = (v) => new Intl.NumberFormat(D.config.LOCALE || "es-PE", { style:"currency", currency:D.config.CURRENCY || "PEN" }).format(Number(v || 0));
  const fmtDate = (v) => v ? new Intl.DateTimeFormat("es-PE", { day:"2-digit", month:"short", year:"numeric" }).format(new Date(`${String(v).slice(0,10)}T12:00:00`)) : "—";
  const fmtDateTime = (v) => v ? new Intl.DateTimeFormat("es-PE", { day:"2-digit", month:"short", hour:"2-digit", minute:"2-digit" }).format(new Date(v)) : "—";
  const icon = (name) => `<i data-lucide="${name}"></i>`;
  const hydrate = () => window.lucide?.createIcons({ attrs:{"stroke-width":1.8} });
  const id = (prefix="x") => `${prefix}-${crypto.randomUUID().slice(0,8)}`;
  const errorText = (e) => ({SUPABASE_NOT_CONFIGURED:"Configura la nueva Supabase en config.js.",PORTAL_ACCESS_DENIED:"Esta cuenta no pertenece a este portal.",INVALID_LOGIN_CREDENTIALS:"Credenciales incorrectas.",PHONE_INVALID:"Número de celular inválido.",AUTH_REQUIRED:"Tu sesión terminó. Ingresa nuevamente.",PASSWORD_TOO_SHORT:"Usa una contraseña de al menos 10 caracteres."}[e?.message] || e?.message || "No se pudo completar la operación.");
  function toast(message, type="info", timeout=4300){const root=$("#toast-root");if(!root)return;const el=document.createElement("div");el.className=`toast ${type}`;el.innerHTML=`${icon(type==="error"?"circle-alert":type==="success"?"circle-check":"info")}<div>${esc(message)}</div>`;root.appendChild(el);hydrate();setTimeout(()=>el.remove(),timeout)}
  const badge = (value) => {const s=String(value||"—").toUpperCase();const cls=/ACTIVE|ONLINE|PAID|APPROVED|READY|OPEN/.test(s)?"green":/SUSPENDED|OFFLINE|REJECTED|FAILED|CANCELLED|LOS/.test(s)?"red":/PENDING|OVERDUE|QUEUED|IN_PROGRESS|PARTIAL|TRIAL/.test(s)?"amber":/OWNER|ADMIN/.test(s)?"violet":"blue";return `<span class="badge ${cls}">${esc(s.replaceAll("_"," "))}</span>`};
  function modal(title, body, onSubmit=null, opts={}){const wrap=document.createElement("div");wrap.className="modal-backdrop";const formId=id("form");wrap.innerHTML=`<div class="modal"><div class="modal-head"><h3>${esc(title)}</h3><button class="modal-close" type="button">${icon("x")}</button></div><div class="modal-body"><form id="${formId}">${body}${onSubmit?`<div class="form-actions"><button type="button" class="btn ghost cancel">Cancelar</button><button class="btn primary submit" type="submit">${opts.submitLabel||"Guardar"}</button></div>`:""}</form></div></div>`;document.body.appendChild(wrap);hydrate();const close=()=>wrap.remove();$(".modal-close",wrap).onclick=close;$(".cancel",wrap)?.addEventListener("click",close);wrap.addEventListener("click",e=>{if(e.target===wrap)close()});if(onSubmit){$("form",wrap).onsubmit=async e=>{e.preventDefault();const b=$(".submit",wrap);b.disabled=true;try{await onSubmit(new FormData(e.currentTarget),wrap);close();toast("Guardado","success")}catch(err){toast(errorText(err),"error");b.disabled=false}}}return wrap}
  const formVal=(fd,n)=>String(fd.get(n)||"").trim();
  const pageHead=(title,subtitle="",actions="")=>`<div class="page-head"><div><h2>${esc(title)}</h2>${subtitle?`<p>${esc(subtitle)}</p>`:""}</div><div class="page-actions">${actions}</div></div>`;
  const kpi=(label,value,ico,color="#3867ff")=>`<div class="kpi" style="--kpi-color:${color};--kpi-soft:${color}14"><div class="kpi-top"><small>${esc(label)}</small><span class="kpi-icon">${icon(ico)}</span></div><strong>${esc(value)}</strong></div>`;
  const table=(heads,rows,empty="Sin registros")=>`<div class="table-card"><div class="table-wrap"><table><thead><tr>${heads.map(x=>`<th>${esc(x)}</th>`).join("")}</tr></thead><tbody>${rows.length?rows.join(""):`<tr><td colspan="${heads.length}" class="empty">${esc(empty)}</td></tr>`}</tbody></table></div></div>`;
  async function q(tableName, configure){let query=D.table(tableName).select("*");if(configure)query=configure(query);const {data,error}=await query;if(error)throw error;return data||[]}
  async function qOne(tableName, configure){let query=D.table(tableName).select("*");if(configure)query=configure(query);const {data,error}=await query.maybeSingle();if(error)throw error;return data||null}
  function configWarning(){return D.configured?"":`<div class="config-alert">Backend pendiente: completa <b>SUPABASE_URL</b> y <b>SUPABASE_PUBLISHABLE_KEY</b> en <code>config.js</code>.</div>`}

  function renderLogin(){
    const isCustomer=portal==="customer";
    const title=portal==="admin"?"Administrador":portal==="isp"?"Acceso ISP":"Mi servicio";
    const sub=isCustomer?"Ingresa con el celular vinculado a tu servicio.":portal==="admin"?"Acceso exclusivo de plataforma.":"Ingresa a la operación de tu empresa.";
    app.innerHTML=`<div class="auth-page"><section class="auth-panel"><a class="auth-brand" href="index.html"><img src="assets/room-mark.svg" alt=""><span>ROOM ISP</span></a><a class="auth-back" href="index.html">${icon("arrow-left")} Inicio</a><div class="auth-box"><span class="portal-pill">${icon(isCustomer?"smartphone":portal==="admin"?"shield-check":"radio-tower")} ${esc(title.toUpperCase())}</span><h1>${esc(title)}</h1><p>${esc(sub)}</p>${configWarning()}${isCustomer?customerLoginForm():staffLoginForm()}</div></section><section class="auth-visual"><div class="auth-network"><div class="network-core"><div class="ring"></div><div class="ring"></div><span class="dot a"></span><span class="dot b"></span><span class="dot c"></span><div class="hub">${icon(isCustomer?"wifi":portal==="admin"?"shield":"router")}</div></div></div></section></div>`;
    hydrate();
    if(isCustomer) bindCustomerLogin(); else bindStaffLogin();
  }
  const staffLoginForm=()=>`<form id="staff-login"><div class="field"><label>Correo o celular</label><div class="input-icon">${icon("user")}<input class="input" name="identity" autocomplete="username" required></div></div><div class="field"><label>Contraseña</label><div class="input-icon">${icon("lock-keyhole")}<input class="input" name="password" type="password" autocomplete="current-password" required></div></div><button class="btn primary block" type="submit">Ingresar ${icon("arrow-right")}</button></form><div class="auth-footer">Sesión independiente y validada contra el rol del portal.</div>`;
  const customerLoginForm=()=>`<div id="customer-login"><form id="otp-request"><div class="field"><label>Celular registrado</label><div class="input-icon">${icon("smartphone")}<input class="input" name="phone" inputmode="tel" autocomplete="tel" placeholder="999 999 999" required></div></div><button class="btn dark block" type="submit">Enviar código ${icon("message-square-code")}</button></form><form id="otp-verify" class="hidden"><div class="field"><label>Código de 6 dígitos</label><input class="input mono" name="token" inputmode="numeric" autocomplete="one-time-code" maxlength="6" required></div><button class="btn primary block" type="submit">Verificar código</button><button class="btn ghost block" type="button" id="otp-back" style="margin-top:8px">Cambiar número</button></form></div><div class="auth-footer">Solo números previamente vinculados por tu ISP pueden iniciar sesión.</div>`;
  function bindStaffLogin(){const form=$("#staff-login");form.onsubmit=async e=>{e.preventDefault();const b=$("button[type=submit]",form);b.disabled=true;try{const fd=new FormData(form);await D.signInStaff(formVal(fd,"identity"),formVal(fd,"password"));await bootAuthenticated()}catch(err){toast(errorText(err),"error");b.disabled=false}}}
  function bindCustomerLogin(){let phone="";const req=$("#otp-request"),ver=$("#otp-verify");req.onsubmit=async e=>{e.preventDefault();const b=$("button",req);b.disabled=true;try{phone=await D.requestCustomerOtp(formVal(new FormData(req),"phone"));req.classList.add("hidden");ver.classList.remove("hidden");$("input",ver).focus();toast("Código enviado","success")}catch(err){toast(errorText(err),"error");b.disabled=false}};ver.onsubmit=async e=>{e.preventDefault();const b=$("button[type=submit]",ver);b.disabled=true;try{await D.verifyCustomerOtp(phone,formVal(new FormData(ver),"token"));await bootAuthenticated()}catch(err){toast(errorText(err),"error");b.disabled=false}};$("#otp-back").onclick=()=>{ver.classList.add("hidden");req.classList.remove("hidden");$("button",req).disabled=false}}

  const adminNav=[
    ["Principal",[["dashboard","layout-dashboard","Inicio"],["organizations","building-2","ISP"]]],
    ["Control",[["security","shield-check","Seguridad"],["audit","list-checks","Auditoría"]]]
  ];
  const ispNav=[
    ["Operación",[["dashboard","layout-dashboard","Inicio"],["customers","users","Clientes"],["plans","gauge","Planes"]]],
    ["Red",[["ftth","map","Red FTTH"],["smartolt","waypoints","SmartOLT"],["hotspot","ticket-check","Hotspot"],["mikrotik","router","MikroTik"]]],
    ["Atención",[["billing","wallet-cards","Cobranza"],["support","life-buoy","Soporte"]]],
    ["Sistema",[["settings","settings-2","Ajustes"]]]
  ];
  function shell(nav){const me=D.identity||{};const orgName=me.organization?.name||me.organization_name||(portal==="admin"?"Plataforma":"ROOM ISP");const display=me.display_name||me.email||me.phone||"Usuario";app.innerHTML=`<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="side-brand"><img src="assets/room-mark.svg" alt=""><span>ROOM ISP</span></div><div class="side-org"><strong>${esc(orgName)}</strong><small>${portal==="admin"?"Control global":"Operación ISP"}</small></div><nav class="nav">${nav.map(([section,items])=>`<div class="nav-section">${esc(section)}</div>${items.map(([key,ico,label])=>`<button class="nav-btn" data-page="${key}">${icon(ico)}<span>${esc(label)}</span></button>`).join("")}`).join("")}</nav><div class="sidebar-foot"><div class="user-mini"><span class="avatar">${esc(display.slice(0,1).toUpperCase())}</span><div><strong>${esc(display)}</strong><small>${esc(me.role||portal)}</small></div><button class="icon-btn" id="logout" title="Cerrar sesión">${icon("log-out")}</button></div></div></aside><main class="main"><header class="topbar"><div style="display:flex;align-items:center;gap:10px"><button class="icon-btn mobile-menu" id="mobile-menu">${icon("menu")}</button><div class="top-title"><h1 id="top-title">ROOM ISP</h1><p id="top-subtitle">Operación conectada</p></div></div><div class="top-actions"><span class="badge green"><span class="glow-dot"></span> Seguro</span><button class="icon-btn" id="refresh-page" title="Actualizar">${icon("refresh-cw")}</button></div></header><div class="content" id="content"></div></main></div>`;hydrate();$("#logout").onclick=async()=>{await D.signOut();location.reload()};$("#mobile-menu").onclick=()=>$("#sidebar").classList.toggle("open");$("#refresh-page").onclick=()=>navigate(state.page,true);$$('.nav-btn').forEach(b=>b.onclick=()=>navigate(b.dataset.page));}
  async function navigate(page,force=false){state.page=page;$$('.nav-btn').forEach(x=>x.classList.toggle("active",x.dataset.page===page));$("#sidebar")?.classList.remove("open");const label=$(`.nav-btn[data-page="${page}"] span`)?.textContent||"ROOM ISP";if($("#top-title"))$("#top-title").textContent=label;const c=$("#content");if(c)c.innerHTML=`<div class="card skeleton" style="height:110px"></div>`;try{if(portal==="admin")await renderAdmin(page,force);else if(portal==="isp")await renderISP(page,force);hydrate()}catch(err){console.error(err);if(c)c.innerHTML=`<div class="notice danger">${esc(errorText(err))}</div>`;toast(errorText(err),"error")}}
  async function renderAdmin(page){
    const c=$("#content");
    if(page==="dashboard"){
      const [orgs,routers,customers,invoices]=await Promise.all([q("organizations",x=>x.order("created_at",{ascending:false})),q("routers",x=>x.limit(1000)),q("customers",x=>x.limit(1)),q("invoices",x=>x.in("status",["PENDING","PARTIAL","OVERDUE"]).limit(1000))]);
      const active=orgs.filter(x=>x.status==="ACTIVE").length, online=routers.filter(x=>x.status==="ONLINE").length, debt=invoices.reduce((a,x)=>a+Number(x.balance||0),0);
      c.innerHTML=pageHead("Control de plataforma","Resumen operativo")+`<div class="grid kpis">${kpi("ISP activos",active,"building-2")}${kpi("Routers online",`${online}/${routers.length}`,"router","#16a36a")}${kpi("ISP registrados",orgs.length,"radio-tower","#7657e8")}${kpi("Cobranza pendiente",fmtMoney(debt),"wallet-cards","#e59b17")}</div><div style="height:16px"></div><div class="grid two"><div class="card"><h3>Estado de ISP</h3>${orgs.slice(0,8).map(o=>`<div class="status-row"><div class="status-main"><span class="status-icon">${icon("building-2")}</span><div><b>${esc(o.name)}</b><small>${esc(o.slug)}</small></div></div>${badge(o.status)}</div>`).join("")||'<div class="empty">Sin ISP</div>'}</div><div class="card"><h3>Red conectada</h3>${routers.slice(0,8).map(r=>`<div class="status-row"><div class="status-main"><span class="status-icon">${icon("router")}</span><div><b>${esc(r.name)}</b><small>${esc(r.model||"MikroTik")} · ${fmtDateTime(r.last_seen_at)}</small></div></div>${badge(r.status)}</div>`).join("")||'<div class="empty">Sin routers</div>'}</div></div>`;return;
    }
    if(page==="organizations"){
      const rows=await q("organizations",x=>x.order("created_at",{ascending:false}));
      c.innerHTML=pageHead("ISP","Empresas conectadas",`<button class="btn primary" id="new-org">${icon("plus")} Nuevo ISP</button>`)+table(["ISP","Estado","Soporte","Zona horaria","Alta",""],rows.map(o=>`<tr><td><b>${esc(o.name)}</b><br><span class="muted mono">${esc(o.slug)}</span></td><td>${badge(o.status)}</td><td>${esc(o.support_phone||"—")}</td><td>${esc(o.timezone||"America/Lima")}</td><td>${fmtDate(o.created_at)}</td><td><button class="btn ghost sm org-state" data-id="${o.id}" data-status="${o.status}">${icon("settings-2")} Gestionar</button></td></tr>`));
      $("#new-org").onclick=()=>modal("Nuevo ISP",`<div class="form-grid"><div class="field span-2"><label>Nombre comercial</label><input class="input" name="name" required></div><div class="field"><label>Slug</label><input class="input" name="slug" required placeholder="mi-isp"></div><div class="field"><label>Teléfono de soporte</label><input class="input" name="support_phone"></div><div class="field span-2"><label>Correo del propietario</label><input class="input" type="email" name="owner_email" required></div><div class="field span-2"><label>Contraseña inicial</label><input class="input" type="password" name="owner_password" minlength="10" required></div></div>`,async fd=>{await D.api("platform_create_organization",{name:formVal(fd,"name"),slug:formVal(fd,"slug"),support_phone:formVal(fd,"support_phone"),owner_email:formVal(fd,"owner_email"),owner_password:formVal(fd,"owner_password")});await navigate("organizations")});
      $$(".org-state").forEach(b=>b.onclick=()=>{const current=b.dataset.status;modal("Estado del ISP",`<div class="field"><label>Estado</label><select class="select" name="status">${["TRIAL","ACTIVE","PAUSED","CANCELLED"].map(s=>`<option ${s===current?"selected":""}>${s}</option>`).join("")}</select></div>`,async fd=>{await D.api("platform_set_organization_status",{organization_id:b.dataset.id,status:formVal(fd,"status")});await navigate("organizations")})});return;
    }
    if(page==="security"){
      const admins=await q("platform_admins",x=>x.limit(100));
      c.innerHTML=pageHead("Seguridad","Acceso de plataforma")+`<div class="grid two"><div class="card"><h3>Controles activos</h3><div class="status-row"><span>Sesiones separadas por portal</span>${badge("ACTIVE")}</div><div class="status-row"><span>RLS multi-tenant</span>${badge("ACTIVE")}</div><div class="status-row"><span>Credenciales sensibles solo servidor</span>${badge("ACTIVE")}</div><div class="status-row"><span>Cliente por OTP</span>${badge("ACTIVE")}</div></div><div class="card"><h3>Administradores</h3>${admins.map(a=>`<div class="status-row"><span class="mono small">${esc(a.user_id)}</span>${badge(a.active? a.role:"DISABLED")}</div>`).join("")||'<div class="empty">Sin administradores</div>'}</div></div><div style="height:16px"></div><div class="card"><h3>Cambiar mi contraseña</h3><p class="muted small">Usa una contraseña única de al menos 10 caracteres.</p><button class="btn ghost" id="change-password">${icon("key-round")} Cambiar contraseña</button></div>`;
      $("#change-password").onclick=()=>modal("Nueva contraseña",`<div class="field"><label>Nueva contraseña</label><input class="input" type="password" name="password" minlength="10" required></div>`,async fd=>{await D.changePassword(formVal(fd,"password"));toast("Contraseña actualizada","success")});return;
    }
    if(page==="audit"){
      const rows=await q("audit_logs",x=>x.order("created_at",{ascending:false}).limit(500));
      c.innerHTML=pageHead("Auditoría","Acciones sensibles y cambios")+table(["Fecha","Acción","Entidad","Actor","ISP"],rows.map(r=>`<tr><td>${fmtDateTime(r.created_at)}</td><td><b>${esc(r.action)}</b></td><td>${esc(r.entity_type)}<br><span class="mono muted">${esc(r.entity_id||"")}</span></td><td class="mono">${esc(r.actor_user_id||r.actor_type||"SYSTEM")}</td><td class="mono">${esc(r.organization_id||"GLOBAL")}</td></tr>`));return;
    }
  }
  async function renderISP(page){
    const c=$("#content"), oid=D.identity.organization_id||D.identity.organization?.id; state.orgId=oid;
    if(!oid) throw new Error("ORGANIZATION_NOT_RESOLVED");
    if(page==="dashboard"){
      const [{data:customers,error:e1},{data:services,error:e2},{data:routers,error:e3},{data:invoices,error:e4},{data:tickets,error:e5}]=await Promise.all([
        D.table("customers").select("id,status").eq("organization_id",oid),D.table("services").select("id,status,access_type").eq("organization_id",oid),D.table("routers").select("id,name,status,model,routeros_version,last_seen_at").eq("organization_id",oid),D.table("invoices").select("id,status,balance,due_date").eq("organization_id",oid).in("status",["PENDING","PARTIAL","OVERDUE"]),D.table("support_tickets").select("id,status").eq("organization_id",oid).neq("status","CLOSED")]);
      if(e1||e2||e3||e4||e5)throw(e1||e2||e3||e4||e5);const sv=services||[],ro=routers||[],inv=invoices||[];const debt=inv.reduce((a,x)=>a+Number(x.balance||0),0);
      c.innerHTML=pageHead("Inicio",D.identity.organization?.name||"Operación ISP",`<button class="btn primary" id="quick-customer">${icon("user-plus")} Cliente</button>`)+`<div class="grid kpis">${kpi("Clientes",customers?.length||0,"users")}${kpi("Servicios activos",sv.filter(x=>x.status==="ACTIVE").length,"wifi","#16a36a")}${kpi("Por cobrar",fmtMoney(debt),"wallet-cards","#e59b17")}${kpi("Routers online",`${ro.filter(x=>x.status==="ONLINE").length}/${ro.length}`,"router","#18b7d8")}</div><div style="height:16px"></div><div class="grid two"><div class="card"><h3>Accesos</h3>${["PPPOE","DHCP","STATIC","HOTSPOT"].map(t=>`<div class="status-row"><span>${t}</span><b>${sv.filter(x=>x.access_type===t&&x.status!=="CANCELLED").length}</b></div>`).join("")}</div><div class="card"><h3>MikroTik</h3>${ro.slice(0,7).map(r=>`<div class="status-row"><div class="status-main"><span class="router-led ${String(r.status).toLowerCase()}"></span><div><b>${esc(r.name)}</b><small>${esc(r.model||"MikroTik")} · ${esc(r.routeros_version||"")}</small></div></div>${badge(r.status)}</div>`).join("")||'<div class="empty">Vincula tu primer MikroTik</div>'}</div></div><div style="height:16px"></div><div class="grid two"><div class="card"><h3>Cobranza</h3><div class="status-row"><span>Facturas pendientes</span><b>${inv.length}</b></div><div class="status-row"><span>Vencidas</span><b>${inv.filter(x=>x.status==="OVERDUE").length}</b></div><div class="status-row"><span>Saldo</span><b>${fmtMoney(debt)}</b></div></div><div class="card"><h3>Soporte</h3><div class="status-row"><span>Tickets abiertos</span><b>${tickets?.length||0}</b></div><div class="status-row"><span>Servicios suspendidos</span><b>${sv.filter(x=>x.status==="SUSPENDED").length}</b></div><div class="status-row"><span>Estado de plataforma</span>${badge("ONLINE")}</div></div></div>`;
      $("#quick-customer").onclick=()=>openCustomerCreate(oid);return;
    }
    if(page==="customers") return renderCustomers(oid);
    if(page==="plans") return renderPlans(oid);
    if(page==="ftth") return renderFtth(oid);
    if(page==="smartolt") return renderSmartOLT(oid);
    if(page==="hotspot") return renderHotspot(oid);
    if(page==="billing") return renderBilling(oid);
    if(page==="support") return renderSupport(oid);
    if(page==="mikrotik") return renderMikrotik(oid);
    if(page==="settings") return renderSettings(oid);
  }

  async function renderCustomers(oid){
    const c=$("#content");
    const {data,error}=await D.table("customers").select("id,code,full_name,nickname,phone,whatsapp,document_number,address,status,created_at,services(id,status,access_type,pppoe_username,dhcp_mac,static_ip,hotspot_username,plans(name,download_mbps,upload_mbps,price))").eq("organization_id",oid).order("full_name");if(error)throw error;const rows=data||[];
    c.innerHTML=pageHead("Clientes","Abonados y servicios",`<button class="btn ghost" id="import-users">${icon("scan-search")} Detectados</button><button class="btn primary" id="new-customer">${icon("user-plus")} Nuevo cliente</button>`)+`<div class="table-card"><div class="table-toolbar"><div class="search">${icon("search")}<input class="input" id="customer-search" placeholder="Buscar cliente, celular o PPPoE"></div><span class="muted small">${rows.length} clientes</span></div><div id="customer-table"></div></div>`;
    const draw=(query="")=>{const term=query.toLowerCase();const filtered=rows.filter(x=>JSON.stringify(x).toLowerCase().includes(term));$("#customer-table").innerHTML=`<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Contacto</th><th>Servicio</th><th>Plan</th><th>Estado</th><th></th></tr></thead><tbody>${filtered.length?filtered.map(x=>{const s=x.services?.find(v=>v.status!=="CANCELLED")||x.services?.[0];const key=s?.pppoe_username||s?.dhcp_mac||s?.static_ip||s?.hotspot_username||"—";return `<tr><td><b>${esc(x.nickname||x.full_name)}</b><br><span class="muted">${esc(x.full_name)}</span></td><td>${esc(x.whatsapp||x.phone)}<br><span class="muted">${esc(x.address||"")}</span></td><td>${esc(s?.access_type||"SIN SERVICIO")}<br><span class="mono muted">${esc(key)}</span></td><td>${esc(s?.plans?.name||"—")}</td><td>${badge(s?.status||x.status)}</td><td><button class="btn ghost sm customer-open" data-id="${x.id}">${icon("chevron-right")}</button></td></tr>`}).join(""):`<tr><td colspan="6" class="empty">Sin clientes</td></tr>`}</tbody></table></div>`;hydrate();$$(".customer-open").forEach(b=>b.onclick=()=>openCustomerDetail(oid,b.dataset.id))};draw();$("#customer-search").oninput=e=>draw(e.target.value);$("#new-customer").onclick=()=>openCustomerCreate(oid);$("#import-users").onclick=()=>openDetectedUsers(oid);hydrate();
  }
  async function openCustomerCreate(oid){
    const [plans,routers]=await Promise.all([q("plans",x=>x.eq("organization_id",oid).eq("active",true).order("price")),q("routers",x=>x.eq("organization_id",oid).order("name"))]);
    modal("Nuevo cliente",`<div class="form-grid"><div class="field span-2"><label>Nombre completo</label><input class="input" name="full_name" required></div><div class="field"><label>Celular de acceso</label><input class="input" name="phone" inputmode="tel" required></div><div class="field"><label>WhatsApp</label><input class="input" name="whatsapp" inputmode="tel"></div><div class="field"><label>DNI / RUC</label><input class="input" name="document_number"></div><div class="field"><label>Alias</label><input class="input" name="nickname"></div><div class="field span-2"><label>Dirección</label><input class="input" name="address"></div><div class="field"><label>Tipo de acceso</label><select class="select" name="access_type"><option>PPPOE</option><option>DHCP</option><option>STATIC</option></select></div><div class="field"><label>Identificador</label><input class="input" name="source_key" required placeholder="usuario PPPoE / MAC / IP"></div><div class="field"><label>Plan</label><select class="select" name="plan_id" required><option value="">Seleccionar</option>${plans.map(p=>`<option value="${p.id}">${esc(p.name)} · ${fmtMoney(p.price)}</option>`).join("")}</select></div><div class="field"><label>MikroTik</label><select class="select" name="router_id" required><option value="">Seleccionar</option>${routers.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join("")}</select></div></div><div class="notice info">El celular se vincula al portal del cliente. PPPoE genera una clave segura; DHCP usa MAC; IP fija usa dirección IP.</div>`,async fd=>{const result=await D.api("isp_create_customer_service",{organization_id:oid,customer:{full_name:formVal(fd,"full_name"),phone:formVal(fd,"phone"),whatsapp:formVal(fd,"whatsapp"),document_number:formVal(fd,"document_number"),nickname:formVal(fd,"nickname"),address:formVal(fd,"address")},service:{access_type:formVal(fd,"access_type"),source_key:formVal(fd,"source_key"),plan_id:formVal(fd,"plan_id"),router_id:formVal(fd,"router_id")}});if(result.access_secret)modal("Acceso creado",`<div class="notice info">Guarda esta clave de instalación. Por seguridad se muestra una sola vez.</div><div class="card" style="margin-top:12px"><b>Usuario</b><div class="mono">${esc(result.access_username||formVal(fd,"source_key"))}</div><br><b>Clave</b><div class="mono">${esc(result.access_secret)}</div></div>`,null);await navigate("customers")},{submitLabel:"Crear y provisionar"});hydrate();
  }
  async function openCustomerDetail(oid,cid){
    const {data,error}=await D.table("customers").select("*,services(*,plans(*),routers(name),service_locations(*))").eq("id",cid).eq("organization_id",oid).single();if(error)throw error;const s=data.services?.find(v=>v.status!=="CANCELLED")||data.services?.[0];
    const locRaw=s?.service_locations,loc=Array.isArray(locRaw)?locRaw[0]:locRaw;
    const body=`<div class="grid two"><div class="card slim"><h3>${esc(data.full_name)}</h3><div class="status-row"><span>Celular</span><b>${esc(data.phone)}</b></div><div class="status-row"><span>Alias</span><b>${esc(data.nickname||"—")}</b></div><div class="status-row"><span>Dirección</span><b>${esc(loc?.address||data.address||"—")}</b></div></div><div class="card slim"><h3>Servicio</h3><div class="status-row"><span>Tipo</span><b>${esc(s?.access_type||"—")}</b></div><div class="status-row"><span>Plan</span><b>${esc(s?.plans?.name||"—")}</b></div><div class="status-row"><span>Estado</span>${badge(s?.status||"—")}</div><div class="status-row"><span>MikroTik</span><b>${esc(s?.routers?.name||"—")}</b></div></div></div>${s?`<div class="form-actions"><button type="button" class="btn ${s.status==="SUSPENDED"?"success":"danger"}" id="service-toggle">${icon(s.status==="SUSPENDED"?"play":"pause")} ${s.status==="SUSPENDED"?"Reconectar":"Suspender"}</button><button type="button" class="btn ghost" id="service-plan">${icon("gauge")} Cambiar plan</button><button type="button" class="btn ghost" id="service-ftth">${icon("map-pin")} FTTH / ubicación</button></div>`:""}`;
    const m=modal("Cliente",body,null);if(s){
      $("#service-toggle",m).onclick=async()=>{try{await D.api("isp_service_action",{organization_id:oid,service_id:s.id,operation:s.status==="SUSPENDED"?"ENABLE":"SUSPEND"});m.remove();toast("Orden enviada al MikroTik","success");await navigate("customers")}catch(e){toast(errorText(e),"error")}};
      $("#service-plan",m).onclick=async()=>{const plans=await q("plans",x=>x.eq("organization_id",oid).eq("active",true).order("price"));modal("Cambiar plan",`<div class="field"><label>Plan</label><select class="select" name="plan_id">${plans.map(p=>`<option value="${p.id}" ${p.id===s.plan_id?"selected":""}>${esc(p.name)} · ${fmtMoney(p.price)}</option>`).join("")}</select></div>`,async fd=>{await D.api("isp_service_action",{organization_id:oid,service_id:s.id,operation:"PLAN_CHANGE",plan_id:formVal(fd,"plan_id")});m.remove();await navigate("customers")})};
      $("#service-ftth",m).onclick=async()=>{const nodes=await q("network_nodes",x=>x.eq("organization_id",oid).in("node_type",["NAP","SPLITTER","OLT"]).order("name"));modal("Ubicación FTTH",`<div class="form-grid"><div class="field span-2"><label>Dirección</label><input class="input" name="address" value="${esc(loc?.address||data.address||"")}"></div><div class="field"><label>Latitud</label><input class="input" type="number" step="any" name="latitude" value="${esc(loc?.latitude||"")}"></div><div class="field"><label>Longitud</label><input class="input" type="number" step="any" name="longitude" value="${esc(loc?.longitude||"")}"></div><div class="field span-2"><label>Nodo de acometida</label><select class="select" name="parent_node_id"><option value="">Sin asignar</option>${nodes.map(n=>`<option value="${n.id}" ${n.id===loc?.parent_node_id?"selected":""}>${esc(n.node_type)} · ${esc(n.name)}</option>`).join("")}</select></div></div><div class="notice info">Asigna la vivienda a su NAP, splitter u OLT. La acometida aparecerá en el mapa.</div>`,async fd=>{await D.api("isp_save_service_location",{organization_id:oid,service_id:s.id,address:formVal(fd,"address"),latitude:formVal(fd,"latitude"),longitude:formVal(fd,"longitude"),parent_node_id:formVal(fd,"parent_node_id")||null});m.remove();await navigate("customers")},{submitLabel:"Guardar ubicación"})};
    }hydrate();
  }
  async function openDetectedUsers(oid){
    const {data,error}=await D.table("router_observations").select("*,routers(name)").eq("organization_id",oid).eq("state","UNMATCHED").order("last_seen_at",{ascending:false}).limit(300);if(error)throw error;const rows=data||[];
    const m=modal("Usuarios detectados",table(["Origen","Identificador","Perfil","Router",""],rows.map(r=>`<tr><td>${badge(r.source_type)}</td><td><b>${esc(r.comment||r.source_key)}</b><br><span class="mono muted">${esc(r.source_key)}</span></td><td>${esc(r.router_profile||"—")}</td><td>${esc(r.routers?.name||"—")}</td><td><button class="btn primary sm import-observation" data-id="${r.id}">Importar</button></td></tr>`)),null);$$(".import-observation",m).forEach(b=>b.onclick=()=>{const r=rows.find(x=>x.id===b.dataset.id);modal("Convertir en cliente",`<div class="form-grid"><div class="field span-2"><label>Nombre</label><input class="input" name="full_name" value="${esc(r.comment||r.source_key)}" required></div><div class="field"><label>Celular</label><input class="input" name="phone" required></div><div class="field"><label>WhatsApp</label><input class="input" name="whatsapp"></div></div>`,async fd=>{await D.api("isp_import_observation",{organization_id:oid,observation_id:r.id,full_name:formVal(fd,"full_name"),phone:formVal(fd,"phone"),whatsapp:formVal(fd,"whatsapp")});m.remove();await navigate("customers")})});hydrate();
  }
  async function renderPlans(oid){
    const c=$("#content");const [plans,profiles]=await Promise.all([q("plans",x=>x.eq("organization_id",oid).order("price")),q("router_profiles",x=>x.eq("organization_id",oid).order("name"))]);
    c.innerHTML=pageHead("Planes","Velocidad, precio y perfil MikroTik",`<button class="btn ghost" id="from-profile">${icon("sparkles")} Desde MikroTik</button><button class="btn primary" id="new-plan">${icon("plus")} Nuevo plan</button>`)+`<div class="grid three">${plans.map(p=>`<div class="card"><div style="display:flex;justify-content:space-between;gap:10px"><div><small class="muted">${esc(p.code)}</small><h3 style="font-size:18px;margin:4px 0">${esc(p.name)}</h3></div>${badge(p.active?"ACTIVE":"DISABLED")}</div><div class="plan-speed"><strong style="font-size:30px">${esc(p.download_mbps)}</strong><span>Mbps</span></div><div class="status-row"><span>Subida</span><b>${esc(p.upload_mbps)} Mbps</b></div><div class="status-row"><span>Mensualidad</span><b>${fmtMoney(p.price)}</b></div><div class="status-row"><span>Perfil</span><b class="mono">${esc(p.router_profile)}</b></div></div>`).join("")||'<div class="empty">Crea tu primer plan</div>'}</div>`;
    const open=(seed={})=>modal("Plan de internet",`<div class="form-grid"><div class="field span-2"><label>Nombre</label><input class="input" name="name" value="${esc(seed.name||"")}" required></div><div class="field"><label>Código</label><input class="input" name="code" value="${esc(seed.code||"")}" required></div><div class="field"><label>Perfil MikroTik</label><input class="input" name="router_profile" value="${esc(seed.router_profile||seed.name||"")}" required></div><div class="field"><label>Descarga Mbps</label><input class="input" type="number" min="1" name="download_mbps" value="${esc(seed.download_mbps||"")}" required></div><div class="field"><label>Subida Mbps</label><input class="input" type="number" min="1" name="upload_mbps" value="${esc(seed.upload_mbps||"")}" required></div><div class="field span-2"><label>Precio mensual</label><input class="input" type="number" min="0" step=".01" name="price" value="${esc(seed.price||"")}" required></div><div class="field span-2"><label>Accesos compatibles</label><div style="display:flex;gap:14px;flex-wrap:wrap"><label><input type="checkbox" name="access" value="PPPOE" checked> PPPoE</label><label><input type="checkbox" name="access" value="DHCP" checked> DHCP</label><label><input type="checkbox" name="access" value="STATIC" checked> IP fija</label><label><input type="checkbox" name="access" value="HOTSPOT"> Hotspot</label></div></div></div>`,async fd=>{await D.api("isp_save_plan",{organization_id:oid,plan:{name:formVal(fd,"name"),code:formVal(fd,"code"),router_profile:formVal(fd,"router_profile"),download_mbps:Number(formVal(fd,"download_mbps")),upload_mbps:Number(formVal(fd,"upload_mbps")),price:Number(formVal(fd,"price")),supported_access:fd.getAll("access")}});await navigate("plans")});
    $("#new-plan").onclick=()=>open();$("#from-profile").onclick=()=>{modal("Perfiles detectados",table(["Perfil","Rate limit","Router",""],profiles.map(p=>`<tr><td><b>${esc(p.name)}</b></td><td class="mono">${esc(p.rate_limit||"—")}</td><td class="mono">${esc(p.router_id)}</td><td><button class="btn primary sm choose-profile" data-id="${p.id}">Usar</button></td></tr>`)),null);setTimeout(()=>{$$(".choose-profile").forEach(b=>b.onclick=()=>{const p=profiles.find(x=>x.id===b.dataset.id);const nums=String(p.rate_limit||"").match(/(\d+)[mM]/g)||[];open({name:p.name,code:p.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,""),router_profile:p.name,download_mbps:nums[1]?parseInt(nums[1]):nums[0]?parseInt(nums[0]):"",upload_mbps:nums[0]?parseInt(nums[0]):""})})},0)};hydrate();
  }
  async function renderFtth(oid){
    const c=$("#content");const [{data:nodes,error:e1},{data:links,error:e2},{data:homes,error:e3},{data:onus,error:e4}]=await Promise.all([D.table("network_nodes").select("*").eq("organization_id",oid),D.table("network_links").select("*").eq("organization_id",oid),D.table("service_locations").select("*,customers(full_name),services(id,access_type,status,pppoe_username,dhcp_mac,static_ip,hotspot_username,plans(name))").eq("organization_id",oid),D.table("olt_onus").select("service_id,status,rx_dbm,serial_number,pon_label").eq("organization_id",oid).not("service_id","is",null)]);if(e1||e2||e3||e4)throw(e1||e2||e3||e4);
    c.innerHTML=pageHead("Red FTTH","Planta y acometidas",`<button class="btn ghost" id="fit-map">${icon("scan")} Ver todo</button>`)+`<div class="map-shell"><div class="map-canvas"><div id="ftth-map"></div></div><aside class="map-side"><h3>Planta</h3><div class="map-legend"><div class="legend-row"><span class="node-dot olt"></span> OLT</div><div class="legend-row"><span class="node-dot nap"></span> NAP</div><div class="legend-row"><span class="node-dot splitter"></span> Splitter</div><div class="legend-row"><span class="node-dot home"></span> Cliente</div></div><div style="height:16px"></div><div class="status-row"><span>Nodos</span><b>${nodes?.length||0}</b></div><div class="status-row"><span>Tramos</span><b>${links?.length||0}</b></div><div class="status-row"><span>Casas</span><b>${(homes||[]).filter(x=>x.latitude&&x.longitude).length}</b></div><div class="status-row"><span>ONU vinculadas</span><b>${(onus||[]).length}</b></div><div class="notice info" style="margin-top:14px">Dibuja nodos y fibra. La casa se asigna desde Clientes y se conecta a su NAP o splitter.</div></aside></div>`;
    if(!window.L)throw new Error("MAP_LIBRARY_UNAVAILABLE");if(state.map){state.map.remove();state.map=null}const center=D.config.DEFAULT_MAP_CENTER||[-12.0464,-77.0428];const map=L.map("ftth-map",{zoomControl:true}).setView(center,D.config.DEFAULT_MAP_ZOOM||13);state.map=map;L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:20,attribution:'&copy; OpenStreetMap'}).addTo(map);
    const bounds=[],nodeById=new Map((nodes||[]).map(n=>[n.id,n])),onuByService=new Map((onus||[]).filter(o=>o.service_id).map(o=>[o.service_id,o]));const nodeIcon=(type)=>L.divIcon({className:"",html:`<div class="ftth-node ftth-${String(type).toLowerCase()}">${icon(type==="OLT"?"radio-tower":type==="NAP"?"box":type==="SPLITTER"?"split":"network")}</div>`,iconSize:[28,28],iconAnchor:[14,14]});
    (links||[]).forEach(l=>{const coords=Array.isArray(l.geometry)?l.geometry:[];if(coords.length>1){const layer=L.polyline(coords.map(x=>[x.lat,x.lng]),{weight:4,opacity:.75,dashArray:l.status==="PLANNED"?"8 8":null}).addTo(map);layer.bindPopup(`<b>${esc(l.name||"Fibra")}</b><br>${esc(l.fiber_count)} hilos · ${esc(l.status)}`);coords.forEach(x=>bounds.push([x.lat,x.lng]))}});
    (nodes||[]).forEach(n=>{const marker=L.marker([Number(n.latitude),Number(n.longitude)],{icon:nodeIcon(n.node_type),draggable:true}).addTo(map);marker.bindPopup(`<b>${esc(n.name)}</b><br>${esc(n.node_type)} · ${esc(n.status)}`);marker.on("dragend",async()=>{const p=marker.getLatLng();try{await D.api("isp_save_network_node",{organization_id:oid,id:n.id,node:{latitude:p.lat,longitude:p.lng}});toast("Ubicación actualizada","success")}catch(e){toast(errorText(e),"error")}});bounds.push([Number(n.latitude),Number(n.longitude)])});
    (homes||[]).filter(h=>h.latitude&&h.longitude).forEach(h=>{const s=h.services,onu=onuByService.get(s?.id),parent=nodeById.get(h.parent_node_id);const pos=[Number(h.latitude),Number(h.longitude)];if(parent)L.polyline([[Number(parent.latitude),Number(parent.longitude)],pos],{weight:2,opacity:.55,dashArray:"4 7"}).addTo(map).bindPopup(`Acometida · ${esc(parent.name)}`);const marker=L.marker(pos,{icon:L.divIcon({className:"",html:`<div class="ftth-node ftth-home">${icon("house")}</div>`,iconSize:[28,28],iconAnchor:[14,14]})}).addTo(map);marker.bindPopup(`<b>${esc(h.customers?.full_name||h.label||"Cliente")}</b><br>${esc(s?.plans?.name||"Sin plan")} · ${esc(s?.status||"")}<br><span class="mono">${esc(s?.pppoe_username||s?.dhcp_mac||s?.static_ip||s?.hotspot_username||"")}</span>${parent?`<br>Nodo: ${esc(parent.name)}`:""}${onu?`<br>ONU ${esc(onu.serial_number)} · ${esc(onu.status)}${onu.rx_dbm==null?"":` · ${esc(onu.rx_dbm)} dBm`}`:""}`);bounds.push(pos)});
    if(map.pm){map.pm.addControls({position:"topleft",drawMarker:true,drawCircleMarker:false,drawPolyline:true,drawRectangle:false,drawPolygon:false,drawCircle:false,drawText:false,editMode:true,dragMode:false,cutPolygon:false,removalMode:false,rotateMode:false});map.on("pm:create",e=>{if(e.shape==="Marker"){const p=e.layer.getLatLng();map.removeLayer(e.layer);modal("Nuevo nodo",`<div class="form-grid"><div class="field"><label>Tipo</label><select class="select" name="node_type"><option>NAP</option><option>SPLITTER</option><option>OLT</option><option>POP</option><option>OTHER</option></select></div><div class="field"><label>Nombre</label><input class="input" name="name" required></div><div class="field"><label>Código</label><input class="input" name="code"></div><div class="field"><label>Estado</label><select class="select" name="status"><option>ACTIVE</option><option>PLANNED</option><option>MAINTENANCE</option></select></div></div>`,async fd=>{await D.api("isp_save_network_node",{organization_id:oid,node:{node_type:formVal(fd,"node_type"),name:formVal(fd,"name"),code:formVal(fd,"code"),status:formVal(fd,"status"),latitude:p.lat,longitude:p.lng}});await renderFtth(oid)})}else if(e.shape==="Line"){const geometry=e.layer.getLatLngs().map(p=>({lat:p.lat,lng:p.lng}));map.removeLayer(e.layer);modal("Tramo de fibra",`<div class="form-grid"><div class="field"><label>Nombre</label><input class="input" name="name" placeholder="Troncal NAP 01"></div><div class="field"><label>Hilos</label><input class="input" type="number" name="fiber_count" value="12" min="1" max="288"></div><div class="field"><label>Estado</label><select class="select" name="status"><option>ACTIVE</option><option>PLANNED</option><option>FAULT</option></select></div></div>`,async fd=>{await D.api("isp_save_network_link",{organization_id:oid,link:{name:formVal(fd,"name"),fiber_count:Number(formVal(fd,"fiber_count")||12),status:formVal(fd,"status"),geometry}});await renderFtth(oid)})}})}
    if(bounds.length)map.fitBounds(bounds,{padding:[40,40],maxZoom:17});$("#fit-map").onclick=()=>bounds.length&&map.fitBounds(bounds,{padding:[40,40],maxZoom:17});hydrate();setTimeout(()=>map.invalidateSize(),80);
  }
  async function renderSmartOLT(oid){
    const c=$("#content");const [status,{data:olts,error:e1},{data:pons,error:e2},{data:onus,error:e3},{data:services,error:e4}]=await Promise.all([D.api("isp_integration_status",{organization_id:oid,provider:"SMARTOLT"}),D.table("olt_devices").select("*").eq("organization_id",oid).order("name"),D.table("olt_pons").select("*,olt_devices(name)").eq("organization_id",oid).order("port"),D.table("olt_onus").select("*,customers(full_name),services(plans(name))").eq("organization_id",oid).order("last_seen_at",{ascending:false}).limit(500),D.table("services").select("id,status,access_type,customers(full_name),plans(name)").eq("organization_id",oid).neq("status","CANCELLED").order("created_at",{ascending:false})]);if(e1||e2||e3||e4)throw(e1||e2||e3||e4);
    const online=(onus||[]).filter(x=>x.status==="ONLINE").length,los=(onus||[]).filter(x=>x.status==="LOS").length,linked=(onus||[]).filter(x=>x.service_id).length;
    c.innerHTML=pageHead("SmartOLT",status.configured?`Sincronizado ${fmtDateTime(status.last_sync_at)}`:"Conecta tu cuenta SmartOLT",`<button class="btn ghost" id="smartolt-config">${icon("key-round")} Configurar</button><button class="btn primary" id="smartolt-sync" ${status.configured?"":"disabled"}>${icon("refresh-cw")} Sincronizar</button>`)+`<div class="grid kpis">${kpi("OLT",olts?.length||0,"radio-tower")}${kpi("ONU online",online,"wifi","#16a36a")}${kpi("LOS",los,"triangle-alert","#d94b59")}${kpi("Vinculadas",linked,"link-2","#7657e8")}</div><div style="height:16px"></div><div class="grid two"><div class="card"><h3>OLT</h3>${(olts||[]).map(o=>`<div class="status-row"><div class="status-main"><span class="status-icon">${icon("radio-tower")}</span><div><b>${esc(o.name)}</b><small>${esc(o.model||o.vendor||"")} · ${esc(o.provider_code||"")}</small></div></div>${badge(o.status)}</div>`).join("")||'<div class="empty">Sin OLT sincronizadas</div>'}</div><div class="card"><h3>PON</h3>${(pons||[]).slice(0,12).map(p=>`<div class="status-row"><span>${esc(p.olt_devices?.name||"OLT")} · ${esc(p.frame??"")}/${esc(p.slot??"")}/${esc(p.port)}</span><span><b>${esc(p.online_onu_count||0)}/${esc(p.onu_count||0)}</b> ${badge(p.status)}</span></div>`).join("")||'<div class="empty">Sin puertos</div>'}</div></div><div style="height:16px"></div>${table(["ONU / Cliente","OLT/PON","Señal RX","Distancia","Estado",""],(onus||[]).map(o=>`<tr><td><b>${esc(o.customers?.full_name||o.name||o.serial_number)}</b><br><span class="mono muted">${esc(o.serial_number)}</span></td><td>${esc(o.olt_name||"—")}<br><span class="muted">${esc(o.pon_label||"—")}</span></td><td><b>${o.rx_dbm==null?"—":`${esc(o.rx_dbm)} dBm`}</b></td><td>${o.distance_m?`${esc(o.distance_m)} m`:"—"}</td><td>${badge(o.status)}</td><td><button class="btn ghost sm onu-link" data-id="${o.id}">${icon(o.service_id?"link":"link-2")} ${o.service_id?"Cambiar":"Vincular"}</button></td></tr>`),"Sin ONU")}`;
    $("#smartolt-config").onclick=()=>modal("Conectar SmartOLT",`<div class="notice info">El token se cifra en el servidor y nunca se guarda en el navegador.</div><div class="field" style="margin-top:14px"><label>Subdominio</label><div style="display:flex;align-items:center;gap:8px"><input class="input" name="subdomain" value="${esc(status.subdomain||"")}" placeholder="miisp"><span class="muted">.smartolt.com</span></div></div><div class="field"><label>API Token</label><input class="input mono" type="password" name="api_key" required></div>`,async fd=>{await D.api("isp_configure_smartolt",{organization_id:oid,subdomain:formVal(fd,"subdomain"),api_key:formVal(fd,"api_key")});await renderSmartOLT(oid)},{submitLabel:"Guardar conexión"});
    $("#smartolt-sync").onclick=async e=>{e.currentTarget.disabled=true;try{const r=await D.smartoltSync(oid,"full");toast(`SmartOLT: ${r.olts||0} OLT · ${r.onus||0} ONU`,"success");await renderSmartOLT(oid)}catch(err){toast(errorText(err),"error");e.currentTarget.disabled=false}};
    $$(".onu-link").forEach(b=>b.onclick=()=>{const onu=(onus||[]).find(x=>x.id===b.dataset.id);modal("Vincular ONU",`<div class="notice info"><b>${esc(onu?.serial_number||"ONU")}</b> · ${esc(onu?.pon_label||"")} ${onu?.rx_dbm==null?"":`· ${esc(onu.rx_dbm)} dBm`}</div><div class="field" style="margin-top:14px"><label>Servicio</label><select class="select" name="service_id" required><option value="">Seleccionar cliente</option>${(services||[]).map(s=>`<option value="${s.id}" ${s.id===onu?.service_id?"selected":""}>${esc(s.customers?.full_name||"Cliente")} · ${esc(s.plans?.name||s.access_type)}</option>`).join("")}</select></div>`,async fd=>{await D.api("isp_link_onu",{organization_id:oid,onu_id:b.dataset.id,service_id:formVal(fd,"service_id")});await renderSmartOLT(oid)},{submitLabel:"Vincular"})});hydrate();
  }
  async function renderHotspot(oid){
    const c=$("#content");const [routers,batches]=await Promise.all([q("routers",x=>x.eq("organization_id",oid).order("name")),q("hotspot_batches",x=>x.eq("organization_id",oid).order("created_at",{ascending:false}).limit(100))]);
    c.innerHTML=pageHead("Hotspot","Fichas y acceso temporal",`<button class="btn primary" id="new-batch">${icon("ticket-plus")} Generar fichas</button>`)+table(["Lote","Cantidad","Perfil","Duración","Precio","Estado","Fecha"],batches.map(b=>`<tr><td><b>${esc(b.name)}</b></td><td>${esc(b.quantity)}</td><td class="mono">${esc(b.profile_name)}</td><td>${b.duration_minutes?`${esc(b.duration_minutes)} min`:"—"}</td><td>${fmtMoney(b.price)}</td><td>${badge(b.status)}</td><td>${fmtDateTime(b.created_at)}</td></tr>`),"Sin lotes");
    $("#new-batch").onclick=()=>modal("Generar fichas Hotspot",`<div class="form-grid"><div class="field span-2"><label>Nombre del lote</label><input class="input" name="name" required placeholder="Fichas fin de semana"></div><div class="field"><label>MikroTik</label><select class="select" name="router_id" required><option value="">Seleccionar</option>${routers.map(r=>`<option value="${r.id}">${esc(r.name)}</option>`).join("")}</select></div><div class="field"><label>Perfil Hotspot</label><input class="input" name="profile_name" required placeholder="1H-10M"></div><div class="field"><label>Cantidad</label><input class="input" type="number" name="quantity" min="1" max="100" value="10" required></div><div class="field"><label>Duración (min)</label><input class="input" type="number" name="duration_minutes" min="1" value="60"></div><div class="field span-2"><label>Precio por ficha</label><input class="input" type="number" step=".01" min="0" name="price" value="0"></div></div>`,async fd=>{const r=await D.api("isp_generate_hotspot_batch",{organization_id:oid,router_id:formVal(fd,"router_id"),name:formVal(fd,"name"),profile_name:formVal(fd,"profile_name"),quantity:Number(formVal(fd,"quantity")),duration_minutes:Number(formVal(fd,"duration_minutes")||0),price:Number(formVal(fd,"price")||0)});showVouchers(r.vouchers||[],formVal(fd,"name"));await navigate("hotspot")},{submitLabel:"Generar y enviar"});hydrate();
  }
  function showVouchers(vouchers,name){const m=modal(`Fichas · ${name}`,`<div class="voucher-sheet">${vouchers.map(v=>`<div class="voucher"><h4>ROOM ISP</h4><small>${esc(name)}</small><div class="credentials"><b>${esc(v.username)}</b><br>${esc(v.password)}</div>${v.duration_minutes?`<small>${esc(v.duration_minutes)} min</small>`:""}</div>`).join("")}</div><div class="form-actions no-print"><button type="button" class="btn primary" id="print-vouchers">${icon("printer")} Imprimir</button></div>`,null);$("#print-vouchers",m).onclick=()=>window.print();hydrate()}

  async function renderBilling(oid){
    const c=$("#content");const [{data:invoices,error:e1},{data:reports,error:e2},{data:channels,error:e3}]=await Promise.all([D.table("invoices").select("*,customers(full_name,phone),services(access_type)").eq("organization_id",oid).order("due_date",{ascending:false}).limit(600),D.table("payment_reports").select("*,customers(full_name),payment_channels(display_name)").eq("organization_id",oid).order("created_at",{ascending:false}).limit(300),D.table("payment_channels").select("*").eq("organization_id",oid).order("sort_order")]);if(e1||e2||e3)throw(e1||e2||e3);
    const pending=(reports||[]).filter(x=>x.status==="PENDING"),debt=(invoices||[]).filter(x=>!["PAID","VOID"].includes(x.status)).reduce((a,x)=>a+Number(x.balance||0),0);
    c.innerHTML=pageHead("Cobranza","Facturas y comprobantes",`<button class="btn ghost" id="payment-method">${icon("qr-code")} Medios de pago</button><button class="btn primary" id="generate-invoices">${icon("receipt-text")} Generar facturas</button>`)+`<div class="grid kpis">${kpi("Saldo pendiente",fmtMoney(debt),"wallet")}${kpi("Por revisar",pending.length,"scan-line","#e59b17")}${kpi("Pagadas",(invoices||[]).filter(x=>x.status==="PAID").length,"circle-check","#16a36a")}${kpi("Vencidas",(invoices||[]).filter(x=>x.status==="OVERDUE").length,"circle-alert","#d94b59")}</div><div style="height:16px"></div><div class="grid two"><div><h3>Comprobantes por revisar</h3>${table(["Cliente","Monto","Canal","Referencia","Estado",""],(reports||[]).slice(0,100).map(r=>`<tr><td><b>${esc(r.customers?.full_name||"—")}</b><br><span class="muted">${fmtDateTime(r.created_at)}</span></td><td><b>${fmtMoney(r.amount)}</b></td><td>${esc(r.payment_channels?.display_name||"—")}</td><td class="mono">${esc(r.operation_reference||"—")}</td><td>${badge(r.status)}</td><td><div class="row-actions">${r.proof_object_path?`<button class="btn ghost sm proof-pay" data-path="${esc(r.proof_object_path)}">${icon("image")} Ver</button>`:""}${r.status==="PENDING"?`<button class="btn success sm approve-pay" data-id="${r.id}">${icon("check")} Aprobar</button><button class="btn danger sm reject-pay" data-id="${r.id}">${icon("x")} Rechazar</button>`:""}</div></td></tr>`),"Sin reportes")}</div><div><h3>Facturas</h3>${table(["Cliente","Vence","Total","Saldo","Estado"],(invoices||[]).slice(0,150).map(i=>`<tr><td><b>${esc(i.customers?.full_name||"—")}</b><br><span class="muted mono">#${esc(String(i.id).slice(0,8).toUpperCase())}</span></td><td>${fmtDate(i.due_date)}</td><td>${fmtMoney(i.total)}</td><td><b>${fmtMoney(i.balance)}</b></td><td>${badge(i.status)}</td></tr>`),"Sin facturas")}</div></div>`;
    $$(".proof-pay").forEach(b=>b.onclick=async()=>{const url=await D.signedUrl("payment-proofs",b.dataset.path,300);if(!url)return toast("No se pudo abrir el comprobante","error");const w=window.open(url,"_blank","noopener,noreferrer");if(!w)location.href=url});
    $$(".approve-pay").forEach(b=>b.onclick=()=>modal("Aprobar pago",`<div class="notice info">Al completar la factura, ROOM ISP encolará la reconexión si el servicio estaba suspendido.</div>`,async()=>{await D.api("isp_review_payment",{organization_id:oid,report_id:b.dataset.id,approve:true});await renderBilling(oid)},{submitLabel:"Aprobar"}));
    $$(".reject-pay").forEach(b=>b.onclick=()=>modal("Rechazar comprobante",`<div class="field"><label>Motivo</label><textarea class="textarea" name="reason" required placeholder="Ej. operación no encontrada"></textarea></div>`,async fd=>{await D.api("isp_review_payment",{organization_id:oid,report_id:b.dataset.id,approve:false,rejection_reason:formVal(fd,"reason")});await renderBilling(oid)},{submitLabel:"Rechazar"}));
    $("#generate-invoices").onclick=async e=>{e.currentTarget.disabled=true;try{const r=await D.api("isp_generate_invoices",{organization_id:oid});toast(`${r.generated||0} facturas generadas`,"success");await renderBilling(oid)}catch(err){toast(errorText(err),"error");e.currentTarget.disabled=false}};
    $("#payment-method").onclick=()=>openPaymentChannels(oid,channels||[]);hydrate();
  }
  async function openPaymentChannels(oid,channels){
    const rows=channels||[];
    const list=rows.length?table(["Medio","Titular / cuenta","QR","Estado",""],rows.map(ch=>`<tr><td><b>${esc(ch.display_name)}</b><br><span class="muted small">${esc(ch.type)}</span></td><td>${esc(ch.receiver_name)}<br><span class="muted">${esc(ch.account_reference||"—")}</span></td><td>${ch.qr_object_path?badge("READY"):"—"}</td><td>${badge(ch.active?"ACTIVE":"DISABLED")}</td><td><button class="btn ghost sm edit-channel" data-id="${ch.id}">${icon("pencil")} Editar</button></td></tr>`),"Sin medios de pago configurados"):'<div class="empty">Configura Yape, Plin, transferencia u otro medio de pago.</div>';
    const parent=modal("Medios de pago",`${list}<div class="form-actions"><button type="button" class="btn primary" id="new-channel">${icon("plus")} Nuevo medio</button></div>`,null);
    const edit=(ch={})=>modal(ch.id?"Editar medio de pago":"Nuevo medio de pago",`<div class="form-grid"><div class="field"><label>Tipo</label><select class="select" name="type">${["YAPE","PLIN","BANK_TRANSFER","CASH","PAYMENT_LINK"].map(x=>`<option value="${x}" ${x===ch.type?"selected":""}>${x.replaceAll("_"," ")}</option>`).join("")}</select></div><div class="field"><label>Nombre visible</label><input class="input" name="display_name" value="${esc(ch.display_name||"")}" placeholder="Yape" required></div><div class="field span-2"><label>Titular</label><input class="input" name="receiver_name" value="${esc(ch.receiver_name||"")}" required></div><div class="field span-2"><label>Número / cuenta / enlace</label><input class="input" name="account_reference" value="${esc(ch.account_reference||"")}"></div><div class="field span-2"><label>Indicaciones</label><textarea class="textarea" name="instructions" placeholder="Indicación breve para el cliente">${esc(ch.instructions||"")}</textarea></div><div class="field span-2"><label>QR de pago (opcional)</label><input class="input" type="file" name="qr" accept="image/png,image/jpeg,image/webp"><small class="muted">PNG/JPG/WebP, máximo 2 MB.</small></div><div class="field span-2"><label style="display:flex;gap:8px;align-items:center"><input type="checkbox" name="active" ${ch.active===false?"":"checked"}> Mostrar al cliente</label></div></div>`,async fd=>{
      const saved=await D.api("isp_save_payment_channel",{organization_id:oid,channel:{id:ch.id||undefined,type:formVal(fd,"type"),display_name:formVal(fd,"display_name"),receiver_name:formVal(fd,"receiver_name"),account_reference:formVal(fd,"account_reference"),instructions:formVal(fd,"instructions"),active:fd.get("active")==="on"}});
      const file=fd.get("qr");
      if(file&&file.size){
        if(file.size>2*1024*1024)throw new Error("QR_TOO_LARGE");
        if(!["image/png","image/jpeg","image/webp"].includes(file.type))throw new Error("QR_FORMAT_INVALID");
        const ext=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";
        const path=`${oid}/${saved.data.id}/${crypto.randomUUID()}.${ext}`;
        await D.upload("payment-assets",path,file);
        await D.api("isp_set_payment_qr",{organization_id:oid,channel_id:saved.data.id,object_path:path});
      }
      parent.remove();await renderBilling(oid);
    },{submitLabel:"Guardar medio"});
    $("#new-channel",parent).onclick=()=>edit({active:true});
    $$(".edit-channel",parent).forEach(b=>b.onclick=()=>edit(rows.find(x=>x.id===b.dataset.id)||{active:true}));
    hydrate();
  }

  async function renderSupport(oid){
    const c=$("#content");const [{data:tickets,error:e1},{data:requests,error:e2}]=await Promise.all([D.table("support_tickets").select("*,customers(full_name,phone)").eq("organization_id",oid).order("created_at",{ascending:false}).limit(300),D.table("customer_requests").select("*,customers(full_name),services(access_type,plans(name))").eq("organization_id",oid).order("created_at",{ascending:false}).limit(200)]);if(e1||e2)throw(e1||e2);const rows=tickets||[],pending=(requests||[]).filter(r=>r.status==="PENDING");
    c.innerHTML=pageHead("Soporte","Tickets y solicitudes")+`${pending.length?`<div class="card"><h3>Solicitudes pendientes</h3>${table(["Cliente","Solicitud","Detalle","Fecha",""],pending.map(r=>`<tr><td><b>${esc(r.customers?.full_name||"—")}</b></td><td>${badge(r.request_type)}</td><td>${esc(r.payload?.plan_name||r.payload?.detail||"—")}</td><td>${fmtDateTime(r.created_at)}</td><td><div class="row-actions"><button class="btn success sm request-review" data-id="${r.id}" data-approve="1">${icon("check")} Aprobar</button><button class="btn danger sm request-review" data-id="${r.id}" data-approve="0">${icon("x")} Rechazar</button></div></td></tr>`),"Sin solicitudes")}</div><div style="height:16px"></div>`:""}${table(["Cliente","Asunto","Prioridad","Estado","Fecha",""],rows.map(t=>`<tr><td><b>${esc(t.customers?.full_name||"—")}</b></td><td>${esc(t.subject)}</td><td>${badge(t.priority)}</td><td>${badge(t.status)}</td><td>${fmtDateTime(t.created_at)}</td><td><button class="btn ghost sm ticket-open" data-id="${t.id}">${icon("message-square")} Abrir</button></td></tr>`),"Sin tickets")}`;
    $$(".ticket-open").forEach(b=>b.onclick=()=>openTicket(oid,b.dataset.id));$$(".request-review").forEach(b=>b.onclick=()=>modal(b.dataset.approve==="1"?"Aprobar solicitud":"Rechazar solicitud",`<div class="notice ${b.dataset.approve==="1"?"info":"warn"}">${b.dataset.approve==="1"?"Si es un cambio de plan, se enviará la orden al MikroTik.":"La solicitud quedará rechazada y no se ejecutará ningún cambio."}</div>`,async()=>{await D.api("isp_review_customer_request",{organization_id:oid,request_id:b.dataset.id,approve:b.dataset.approve==="1"});await renderSupport(oid)},{submitLabel:b.dataset.approve==="1"?"Aprobar":"Rechazar"}));hydrate();
  }
  async function openTicket(oid,tid){const [{data:t,error:e1},{data:messages,error:e2}]=await Promise.all([D.table("support_tickets").select("*,customers(full_name)").eq("id",tid).single(),D.table("support_messages").select("*").eq("ticket_id",tid).order("created_at")]);if(e1||e2)throw(e1||e2);const m=modal(t.subject,`<div class="notice info">${esc(t.customers?.full_name||"Cliente")} · ${esc(t.priority)}</div><div style="margin:14px 0;display:grid;gap:8px">${(messages||[]).map(x=>`<div class="card slim"><b>${esc(x.sender_type)}</b><p style="margin:5px 0 0">${esc(x.body)}</p><small class="muted">${fmtDateTime(x.created_at)}</small></div>`).join("")||'<div class="empty">Sin mensajes</div>'}</div><form id="ticket-reply"><div class="field"><textarea class="textarea" name="body" required placeholder="Responder..."></textarea></div><div class="form-actions"><select class="select" name="status" style="max-width:170px"><option ${t.status==="OPEN"?"selected":""}>OPEN</option><option ${t.status==="IN_PROGRESS"?"selected":""}>IN_PROGRESS</option><option>RESOLVED</option><option>CLOSED</option></select><button class="btn primary" type="submit">Enviar</button></div></form>`,null);$("#ticket-reply",m).onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await D.api("isp_reply_ticket",{organization_id:oid,ticket_id:tid,body:formVal(fd,"body"),status:formVal(fd,"status")});m.remove();await renderSupport(oid)}catch(err){toast(errorText(err),"error")}};hydrate()}
  async function renderMikrotik(oid){
    const c=$("#content");const [{data:routers,error:e1},{data:commands,error:e2}]=await Promise.all([D.table("routers").select("*").eq("organization_id",oid).order("name"),D.table("network_commands").select("id,router_id,command_type,status,last_error,created_at,acked_at,ack_payload").eq("organization_id",oid).order("created_at",{ascending:false}).limit(80)]);if(e1||e2)throw(e1||e2);
    c.innerHTML=pageHead("MikroTik","Vinculación automática y control seguro",`<button class="btn primary" id="link-router">${icon("link-2")} Vincular MikroTik</button>`)+`<div class="grid two"><div class="card"><h3>Routers</h3>${(routers||[]).map(r=>`<div class="router-card" style="margin-bottom:9px"><span class="router-led ${String(r.status).toLowerCase()}"></span><div><b>${esc(r.name)}</b><small>${esc(r.model||"MikroTik")} · RouterOS ${esc(r.routeros_version||"—")}<br>${fmtDateTime(r.last_seen_at)}</small></div><button class="btn ghost sm router-open" data-id="${r.id}">Abrir</button></div>`).join("")||'<div class="empty">No hay routers vinculados</div>'}</div><div class="card"><h3>Órdenes recientes</h3>${(commands||[]).slice(0,10).map(x=>`<div class="status-row"><div><b>${esc(x.command_type)}</b><br><span class="muted small">${fmtDateTime(x.created_at)}</span></div>${badge(x.status)}</div>`).join("")||'<div class="empty">Sin órdenes</div>'}</div></div>`;
    $("#link-router").onclick=async()=>{try{const issued=await D.mikrotikInstaller(oid,"MikroTik");const tpl=await fetch("mikrotik/roomisp-agent.rsc",{cache:"no-store"}).then(r=>{if(!r.ok)throw new Error("INSTALLER_TEMPLATE_NOT_FOUND");return r.text()});const script=tpl.replaceAll("__ROOM_ENROLL_URL__",issued.enroll_url).replaceAll("__ROOM_AGENT_URL__",issued.agent_url).replaceAll("__ROOM_ENROLL_CODE__",issued.enrollment_code);const m=modal("Vincular MikroTik",`<div class="notice info">Copia el script completo en <b>New Terminal</b>. El router saldrá por HTTPS hacia Supabase; no necesita VPN ni abrir puertos de administración.</div><div class="field" style="margin-top:12px"><textarea class="textarea mono" id="installer-script" style="min-height:300px" readonly>${esc(script)}</textarea></div><div class="form-actions"><button type="button" class="btn primary" id="copy-script">${icon("copy")} Copiar instalador</button></div>`,null);$("#copy-script",m).onclick=async()=>{await navigator.clipboard.writeText(script);toast("Instalador copiado","success")};hydrate()}catch(e){toast(errorText(e),"error")}};
    $$(".router-open").forEach(b=>b.onclick=()=>openRouter(oid,b.dataset.id));hydrate();
  }
  async function openRouter(oid,rid){
    const [{data:r,error:e1},{data:obs,error:e2},{data:profiles,error:e3},{data:inventory,error:e4},{data:history,error:e5}]=await Promise.all([D.table("routers").select("*").eq("id",rid).eq("organization_id",oid).single(),D.table("router_observations").select("*").eq("router_id",rid).order("source_type").limit(500),D.table("router_profiles").select("*").eq("router_id",rid).order("name"),D.table("router_inventory_items").select("*").eq("router_id",rid).order("item_type").limit(500),D.table("network_commands").select("*").eq("router_id",rid).order("created_at",{ascending:false}).limit(60)]);if(e1||e2||e3||e4||e5)throw(e1||e2||e3||e4||e5);
    const m=modal(r.name,`<div class="grid two"><div class="card slim"><h3>Equipo</h3><div class="status-row"><span>Estado</span>${badge(r.status)}</div><div class="status-row"><span>Modelo</span><b>${esc(r.model||"—")}</b></div><div class="status-row"><span>RouterOS</span><b>${esc(r.routeros_version||"—")}</b></div><div class="status-row"><span>Arquitectura</span><b>${esc(r.architecture||"—")}</b></div><div class="status-row"><span>Último contacto</span><b>${fmtDateTime(r.last_seen_at)}</b></div></div><div class="card slim"><h3>Inventario</h3><div class="status-row"><span>PPPoE / DHCP / IP / Hotspot</span><b>${obs?.length||0}</b></div><div class="status-row"><span>Perfiles PPP</span><b>${profiles?.length||0}</b></div><div class="status-row"><span>Elementos de red</span><b>${inventory?.length||0}</b></div><button class="btn soft block" id="inventory-now" style="margin-top:10px">${icon("scan-search")} Sincronizar inventario</button></div></div><div style="height:14px"></div><div class="terminal"><div class="terminal-head"><span class="terminal-dots"><span></span><span></span><span></span></span> Consola segura ROOM ISP</div><div class="terminal-body" id="terminal-body">${(history||[]).filter(x=>x.command_type==="TERMINAL_READ").slice(0,12).reverse().map(x=>`<div class="terminal-line"><span class="prompt">$ ${esc(x.payload?.terminal_alias||"comando")}</span>\n<span class="out">${esc(x.ack_payload?.output||x.last_error||x.status)}</span></div>`).join("")||'<span class="out">Selecciona un comando de diagnóstico. No se exponen credenciales ni una shell arbitraria.</span>'}</div><div class="terminal-actions"><select class="select" id="terminal-command"><option value="system_resource">Sistema / recursos</option><option value="interfaces">Interfaces</option><option value="ip_addresses">Direcciones IP</option><option value="routes">Rutas</option><option value="ppp_active">PPPoE activos</option><option value="dhcp_leases">DHCP leases</option><option value="hotspot_active">Hotspot activos</option><option value="ping_gateway">Ping 8.8.8.8</option></select><button class="btn" id="terminal-run">${icon("play")} Ejecutar</button></div></div><div style="height:14px"></div><div class="card slim"><h3>Detectado automáticamente</h3>${table(["Tipo","Elemento","Detalle"],(inventory||[]).slice(0,80).map(x=>`<tr><td>${esc(x.item_type)}</td><td><b>${esc(x.item_key)}</b></td><td class="mono">${esc(JSON.stringify(x.data||{}).slice(0,160))}</td></tr>`),"Sin inventario técnico")}</div>`,null);
    $("#inventory-now",m).onclick=async e=>{e.currentTarget.disabled=true;try{await D.api("isp_router_action",{organization_id:oid,router_id:rid,operation:"INVENTORY_NOW"});toast("Sincronización encolada","success")}catch(err){toast(errorText(err),"error");e.currentTarget.disabled=false}};
    $("#terminal-run",m).onclick=async e=>{e.currentTarget.disabled=true;const alias=$("#terminal-command",m).value;try{const result=await D.api("isp_router_terminal",{organization_id:oid,router_id:rid,terminal_alias:alias});$("#terminal-body",m).insertAdjacentHTML("beforeend",`<div class="terminal-line"><span class="prompt">$ ${esc(alias)}</span>\n<span class="out">Encolado ${esc(result.command_id)}. El agente devolverá el resultado en su próximo ciclo.</span></div>`);$("#terminal-body",m).scrollTop=$("#terminal-body",m).scrollHeight;toast("Comando seguro encolado","success")}catch(err){toast(errorText(err),"error")}finally{e.currentTarget.disabled=false}};hydrate();
  }

  async function renderSettings(oid){
    const c=$("#content");const [org,settings]=await Promise.all([qOne("organizations",x=>x.eq("id",oid)),qOne("organization_settings",x=>x.eq("organization_id",oid))]);
    c.innerHTML=pageHead("Ajustes","Cobranza y operación")+`<div class="grid two"><form class="card" id="org-settings"><h3>Facturación</h3><div class="form-grid"><div class="field"><label>Día de vencimiento</label><input class="input" type="number" min="1" max="28" name="due_day" value="${esc(settings?.due_day||15)}"></div><div class="field"><label>Días de gracia</label><input class="input" type="number" min="0" max="31" name="grace_days" value="${esc(settings?.grace_days||0)}"></div><div class="field span-2"><label><input type="checkbox" name="auto_suspend" ${settings?.auto_suspend!==false?"checked":""}> Suspender automáticamente por deuda</label></div><div class="field span-2"><label><input type="checkbox" name="customer_portal_enabled" ${settings?.customer_portal_enabled!==false?"checked":""}> Portal cliente activo</label></div></div><button class="btn primary" type="submit">Guardar</button></form><div class="card"><h3>Empresa</h3><div class="status-row"><span>Nombre</span><b>${esc(org?.name||"—")}</b></div><div class="status-row"><span>Soporte</span><b>${esc(org?.support_phone||"—")}</b></div><div class="status-row"><span>Zona horaria</span><b>${esc(org?.timezone||"America/Lima")}</b></div><button class="btn ghost" id="change-password" style="margin-top:12px">${icon("key-round")} Cambiar mi contraseña</button></div></div>`;
    $("#org-settings").onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await D.api("isp_save_settings",{organization_id:oid,settings:{due_day:Number(formVal(fd,"due_day")),grace_days:Number(formVal(fd,"grace_days")),auto_suspend:fd.get("auto_suspend")==="on",customer_portal_enabled:fd.get("customer_portal_enabled")==="on"}});toast("Ajustes guardados","success")}catch(err){toast(errorText(err),"error")}};$("#change-password").onclick=()=>modal("Nueva contraseña",`<div class="field"><label>Nueva contraseña</label><input class="input" type="password" name="password" minlength="10" required></div>`,async fd=>D.changePassword(formVal(fd,"password")));hydrate();
  }
  async function bootCustomer(){
    const cid=D.identity.customer_id;state.customerId=cid;if(!cid)throw new Error("CUSTOMER_NOT_RESOLVED");
    app.innerHTML=`<div class="customer-shell"><header class="customer-top"><a class="customer-brand" href="cliente.html"><img src="assets/room-mark.svg" alt=""><span>ROOM ISP</span></a><div style="display:flex;gap:8px;align-items:center"><span class="muted small" id="customer-name"></span><button class="icon-btn" id="customer-logout">${icon("log-out")}</button></div></header><main class="customer-main"><div id="customer-content"></div></main></div>`;hydrate();$("#customer-logout").onclick=async()=>{await D.signOut();location.reload()};await renderCustomer();
  }
  async function customerData(){
    const cid=state.customerId;const [{data:customer,error:e1},{data:services,error:e2},{data:invoices,error:e3},{data:channels,error:e4},{data:tickets,error:e5},{data:plans,error:e6}]=await Promise.all([
      D.table("customers").select("*").eq("id",cid).single(),D.table("services").select("*,plans(*),service_locations(*)").eq("customer_id",cid).order("created_at",{ascending:false}),D.table("invoices").select("*").eq("customer_id",cid).order("due_date",{ascending:false}).limit(100),D.table("payment_channels").select("*").eq("organization_id",D.identity.organization_id).eq("active",true).order("sort_order"),D.table("support_tickets").select("*").eq("customer_id",cid).order("created_at",{ascending:false}).limit(100),D.table("plans").select("*").eq("organization_id",D.identity.organization_id).eq("active",true).order("price")]);if(e1||e2||e3||e4||e5||e6)throw(e1||e2||e3||e4||e5||e6);return{customer,services:services||[],invoices:invoices||[],channels:channels||[],tickets:tickets||[],plans:plans||[]};
  }
  async function renderCustomer(){
    const c=$("#customer-content");c.innerHTML=`<div class="card skeleton" style="height:180px"></div>`;const data=await customerData();state.cache.customer=data;$("#customer-name").textContent=data.customer.nickname||data.customer.full_name;
    const tabs=[["home","house","Inicio"],["payments","receipt-text","Pagos"],["plans","gauge","Planes"],["support","life-buoy","Soporte"],["profile","user-round","Perfil"]];
    const tabHtml=`<div class="customer-tabs">${tabs.map(([k,i,l])=>`<button class="customer-tab ${state.customerTab===k?"active":""}" data-tab="${k}">${icon(i)} ${l}</button>`).join("")}</div><div id="customer-tab-body"></div>`;c.innerHTML=tabHtml;hydrate();$$('.customer-tab').forEach(b=>b.onclick=()=>{state.customerTab=b.dataset.tab;renderCustomerTab(data)});await renderCustomerTab(data);
  }
  async function renderCustomerTab(data){
    const body=$("#customer-tab-body"),svc=data.services.find(x=>x.status!=="CANCELLED")||data.services[0],openInv=data.invoices.find(x=>!["PAID","VOID"].includes(x.status));
    if(state.customerTab==="home"){
      let qr=null;const channel=data.channels.find(x=>x.qr_object_path)||data.channels[0];if(channel?.qr_object_path)qr=await D.signedUrl("payment-assets",channel.qr_object_path,600);
      body.innerHTML=`<div class="customer-hero"><section class="service-card"><span class="signal"><span class="glow-dot"></span> ${svc?.status==="ACTIVE"?"INTERNET ACTIVO":esc(svc?.status||"SIN SERVICIO")}</span><h2>${esc(svc?.plans?.name||"Tu servicio")}</h2><p>${esc(svc?.access_type||"")}</p><div class="plan-speed"><strong>${esc(svc?.plans?.download_mbps||"—")}</strong><span>Mbps</span></div></section><section class="bill-card"><small class="muted">${openInv?"Próximo pago":"Cuenta al día"}</small><div class="amount">${openInv?fmtMoney(openInv.balance):fmtMoney(0)}</div><p class="muted small">${openInv?`Vence ${fmtDate(openInv.due_date)}`:"Gracias por estar al día"}</p>${qr?`<div class="qr-box"><img src="${esc(qr)}" alt="QR de pago"></div>`:""}${channel?`<p class="small"><b>${esc(channel.display_name)}</b><br>${esc(channel.receiver_name)} · ${esc(channel.account_reference||"")}</p>`:""}${openInv?`<button class="btn primary block" id="report-pay">${icon("scan-line")} Reportar pago</button>`:""}</section></div><div style="height:16px"></div><div class="grid two"><div class="card"><h3>Mi conexión</h3><div class="status-row"><span>Estado</span>${badge(svc?.status||"—")}</div><div class="status-row"><span>Plan</span><b>${esc(svc?.plans?.name||"—")}</b></div><div class="status-row"><span>Mensualidad</span><b>${fmtMoney(svc?.plans?.price||0)}</b></div><div class="status-row"><span>Pagado hasta</span><b>${fmtDate(svc?.paid_until)}</b></div></div><div class="card"><h3>Alta velocidad</h3><div class="speed-meter"><div class="speed-value"><strong>${esc(svc?.plans?.download_mbps||0)}</strong><small>Mbps contratados</small></div></div></div></div>`;if(openInv)$("#report-pay").onclick=()=>customerReportPayment(openInv,data.channels);hydrate();return;
    }
    if(state.customerTab==="payments"){
      body.innerHTML=pageHead("Mis pagos","")+table(["Periodo","Vence","Total","Saldo","Estado",""],data.invoices.map(i=>`<tr><td>${fmtDate(i.period_start)}</td><td>${fmtDate(i.due_date)}</td><td>${fmtMoney(i.total)}</td><td><b>${fmtMoney(i.balance)}</b></td><td>${badge(i.status)}</td><td>${!["PAID","VOID"].includes(i.status)?`<button class="btn primary sm customer-pay" data-id="${i.id}">Pagar</button>`:""}</td></tr>`),"Sin facturas");$$(".customer-pay").forEach(b=>b.onclick=()=>customerReportPayment(data.invoices.find(i=>i.id===b.dataset.id),data.channels));hydrate();return;
    }
    if(state.customerTab==="plans"){
      body.innerHTML=pageHead("Planes disponibles","")+`<div class="grid three">${data.plans.map(p=>`<div class="card"><small class="muted">${esc(p.code)}</small><h3 style="font-size:18px;margin-top:4px">${esc(p.name)}</h3><div class="plan-speed"><strong style="font-size:32px">${esc(p.download_mbps)}</strong><span> Mbps</span></div><div class="status-row"><span>Mensualidad</span><b>${fmtMoney(p.price)}</b></div><button class="btn ${p.id===svc?.plan_id?"soft":"primary"} block request-plan" data-id="${p.id}" ${p.id===svc?.plan_id?"disabled":""}>${p.id===svc?.plan_id?"Plan actual":"Solicitar cambio"}</button></div>`).join("")}</div>`;$$('.request-plan').forEach(b=>b.onclick=async()=>{try{await D.api("customer_request_plan_change",{service_id:svc.id,plan_id:b.dataset.id});toast("Solicitud enviada","success")}catch(e){toast(errorText(e),"error")}});hydrate();return;
    }
    if(state.customerTab==="support"){
      body.innerHTML=pageHead("Soporte","",`<button class="btn primary" id="new-ticket">${icon("plus")} Nuevo ticket</button>`)+table(["Asunto","Prioridad","Estado","Fecha",""],data.tickets.map(t=>`<tr><td><b>${esc(t.subject)}</b></td><td>${badge(t.priority)}</td><td>${badge(t.status)}</td><td>${fmtDateTime(t.created_at)}</td><td><button class="btn ghost sm client-ticket" data-id="${t.id}">${icon("message-square")}</button></td></tr>`),"Sin tickets");$("#new-ticket").onclick=()=>modal("Nuevo ticket",`<div class="field"><label>Asunto</label><input class="input" name="subject" required></div><div class="field"><label>Prioridad</label><select class="select" name="priority"><option>NORMAL</option><option>LOW</option><option>HIGH</option><option>CRITICAL</option></select></div><div class="field"><label>Detalle</label><textarea class="textarea" name="detail" required></textarea></div>`,async fd=>{await D.api("customer_create_ticket",{subject:formVal(fd,"subject"),priority:formVal(fd,"priority"),detail:formVal(fd,"detail"),service_id:svc?.id});await renderCustomer()});$$('.client-ticket').forEach(b=>b.onclick=()=>openCustomerTicket(b.dataset.id));hydrate();return;
    }
    if(state.customerTab==="profile"){
      const loc=svc?.service_locations?.[0]||svc?.service_locations||{};body.innerHTML=pageHead("Mi perfil","")+`<div class="grid two"><form class="card" id="profile-form"><div style="display:flex;align-items:center;gap:14px;margin-bottom:18px"><span class="profile-avatar">${esc((data.customer.nickname||data.customer.full_name).slice(0,1).toUpperCase())}</span><div><h3 style="margin:0">${esc(data.customer.full_name)}</h3><span class="muted small">${esc(data.customer.phone)}</span></div></div><div class="field"><label>Nombre visible / alias</label><input class="input" name="nickname" value="${esc(data.customer.nickname||"")}"></div><div class="field"><label>Correo</label><input class="input" type="email" name="email" value="${esc(data.customer.email||"")}"></div><div class="field"><label>WhatsApp</label><input class="input" name="whatsapp" value="${esc(data.customer.whatsapp||data.customer.phone||"")}"></div><button class="btn primary" type="submit">Guardar perfil</button></form><form class="card" id="location-form"><h3>Ubicación del servicio</h3><div class="field"><label>Dirección</label><input class="input" name="address" value="${esc(loc.address||data.customer.address||"")}"></div><div class="field"><label>Referencia</label><input class="input" name="reference" value="${esc(data.customer.address_reference||"")}"></div><input type="hidden" name="latitude" value="${esc(loc.latitude||"")}"><input type="hidden" name="longitude" value="${esc(loc.longitude||"")}"><button class="btn ghost block" type="button" id="use-location">${icon("locate-fixed")} Usar mi ubicación</button><button class="btn primary block" type="submit" style="margin-top:8px">Guardar ubicación</button></form></div>`;
      $("#profile-form").onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await D.api("customer_update_profile",{nickname:formVal(fd,"nickname"),email:formVal(fd,"email"),whatsapp:formVal(fd,"whatsapp")});toast("Perfil actualizado","success");await renderCustomer()}catch(err){toast(errorText(err),"error")}};$("#use-location").onclick=()=>navigator.geolocation?.getCurrentPosition(pos=>{const f=$("#location-form");f.elements.latitude.value=pos.coords.latitude;f.elements.longitude.value=pos.coords.longitude;toast("Ubicación capturada","success")},()=>toast("No se pudo obtener la ubicación","error"),{enableHighAccuracy:true,timeout:10000});$("#location-form").onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await D.api("customer_update_location",{service_id:svc?.id,address:formVal(fd,"address"),reference:formVal(fd,"reference"),latitude:Number(formVal(fd,"latitude"))||null,longitude:Number(formVal(fd,"longitude"))||null});toast("Ubicación actualizada","success")}catch(err){toast(errorText(err),"error")}};hydrate();return;
    }
  }
  async function customerReportPayment(invoice,channels){
    modal("Reportar pago",`<div class="notice info">Tu ISP validará el comprobante. Si el servicio está suspendido y la factura queda pagada, ROOM ISP encolará la reconexión.</div><div class="form-grid" style="margin-top:14px"><div class="field"><label>Monto</label><input class="input" type="number" step=".01" min="0.01" name="amount" value="${esc(invoice.balance)}" required></div><div class="field"><label>Medio</label><select class="select" name="channel_id" required>${channels.map(ch=>`<option value="${ch.id}">${esc(ch.display_name)}</option>`).join("")}</select></div><div class="field span-2"><label>Número de operación</label><input class="input" name="operation_reference" required></div><div class="field span-2"><label>Comprobante</label><input class="input" type="file" name="proof" accept="image/png,image/jpeg,image/webp" required></div></div>`,async fd=>{const file=fd.get("proof");if(!file||!file.size)throw new Error("PROOF_REQUIRED");if(file.size>2*1024*1024)throw new Error("PROOF_TOO_LARGE");const ext=(file.name.split(".").pop()||"webp").toLowerCase();const path=`${state.customerId}/${crypto.randomUUID()}.${ext}`;await D.upload("payment-proofs",path,file);await D.api("customer_report_payment",{invoice_id:invoice.id,channel_id:formVal(fd,"channel_id"),amount:Number(formVal(fd,"amount")),operation_reference:formVal(fd,"operation_reference"),proof_object_path:path});await renderCustomer()},{submitLabel:"Enviar comprobante"});hydrate();
  }
  async function openCustomerTicket(tid){const [{data:t,error:e1},{data:messages,error:e2}]=await Promise.all([D.table("support_tickets").select("*").eq("id",tid).single(),D.table("support_messages").select("*").eq("ticket_id",tid).order("created_at")]);if(e1||e2)throw(e1||e2);const m=modal(t.subject,`<div style="display:grid;gap:8px">${(messages||[]).map(x=>`<div class="card slim"><b>${esc(x.sender_type==="CUSTOMER"?"Tú":"Soporte")}</b><p style="margin:5px 0">${esc(x.body)}</p><small class="muted">${fmtDateTime(x.created_at)}</small></div>`).join("")}</div>${t.status!=="CLOSED"?`<form id="customer-reply" style="margin-top:14px"><div class="field"><textarea class="textarea" name="body" required></textarea></div><button class="btn primary" type="submit">Responder</button></form>`:""}`,null);if($("#customer-reply",m))$("#customer-reply",m).onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.currentTarget);try{await D.api("customer_reply_ticket",{ticket_id:tid,body:formVal(fd,"body")});m.remove();await renderCustomer()}catch(err){toast(errorText(err),"error")}};hydrate()}
  async function bootAuthenticated(){
    if(portal==="customer"){await bootCustomer();return}
    shell(portal==="admin"?adminNav:ispNav);await navigate("dashboard");
    if(D.identity?.must_change_password){modal("Cambia tu contraseña",`<div class="notice warn">Esta cuenta usa una contraseña inicial. Cámbiala antes de continuar.</div><div class="field" style="margin-top:14px"><label>Nueva contraseña</label><input class="input" type="password" minlength="10" name="password" required></div>`,async fd=>{await D.changePassword(formVal(fd,"password"));toast("Contraseña actualizada","success")},{submitLabel:"Actualizar contraseña"})}
  }
  async function start(){try{const ready=await D.init();if(ready.session&&ready.identity)await bootAuthenticated();else renderLogin()}catch(e){console.error(e);renderLogin();toast(errorText(e),"error")}}
  start();
})();
