import { adminClient, cleanText, decryptSecret, handleError, HttpError, json, options, parseJson, requireOrgAccess, requireUser, validUuid } from "../_shared/core.ts";

const val=(o:any,...keys:string[])=>{for(const k of keys)if(o?.[k]!==undefined&&o?.[k]!==null&&String(o[k])!=="")return o[k];return null};
const num=(v:any)=>{if(v===null||v===undefined)return null;const n=Number(String(v).replace(/[^0-9.-]/g,""));return Number.isFinite(n)?n:null};
const txt=(v:any,max=180)=>cleanText(v,max)||null;
const arr=(v:any)=>Array.isArray(v)?v:Array.isArray(v?.response)?v.response:Array.isArray(v?.data)?v.data:[];
const statusMap=(v:any)=>{const s=String(v??"").toUpperCase().replace(/\s+/g,"_");if(/ONLINE|UP|WORKING|ACTIVE/.test(s))return"ONLINE";if(/LOS/.test(s))return"LOS";if(/DYING/.test(s))return"DYING_GASP";if(/OFFLINE|DOWN|INACTIVE/.test(s))return"OFFLINE";return"UNKNOWN"};
const oltStatus=(v:any)=>{const s=String(v??"").toUpperCase();if(/UP|ONLINE|ACTIVE/.test(s))return"ONLINE";if(/DEGRADED|WARNING/.test(s))return"DEGRADED";if(/DOWN|OFFLINE/.test(s))return"OFFLINE";return"UNKNOWN"};
function keyFor(o:any){return String(val(o,"unique_external_id","onu_external_id","id","onu_id","external_id","serial_number","sn","serial")||"").trim()}

Deno.serve(async(req:Request)=>{
  const pre=options(req);if(pre)return pre;if(req.method!=="POST")return json({ok:false,error:"METHOD_NOT_ALLOWED"},405);
  try{
    const db=adminClient(),user=await requireUser(req,db),body=await parseJson(req),oid=body.organization_id;if(!validUuid(oid))throw new HttpError(400,"ORGANIZATION_ID_INVALID");await requireOrgAccess(db,user.id,oid,["OWNER","ADMIN","TECHNICIAN"]);
    const{data:conn}=await db.from("integration_connections").select("*").eq("organization_id",oid).eq("provider","SMARTOLT").maybeSingle();if(!conn?.secret_ciphertext||!conn?.secret_iv)throw new HttpError(400,"SMARTOLT_NOT_CONFIGURED");
    const sub=String(conn.public_config?.subdomain||"").replace(/\.smartolt\.com$/i,"");if(!/^[a-z0-9-]+$/i.test(sub))throw new HttpError(400,"SMARTOLT_SUBDOMAIN_INVALID");const token=await decryptSecret(conn.secret_ciphertext,conn.secret_iv),base=`https://${sub}.smartolt.com`;
    async function get(path:string){const ctrl=new AbortController();const timer=setTimeout(()=>ctrl.abort(),20000);try{const r=await fetch(`${base}${path}`,{headers:{"X-Token":token,"Accept":"application/json"},signal:ctrl.signal});const raw=await r.text();let j:any;try{j=JSON.parse(raw)}catch{throw new Error(`SMARTOLT_BAD_JSON_${r.status}`)}if(!r.ok||j?.status===false)throw new Error(`SMARTOLT_${r.status}_${txt(j?.error||j?.message,120)||"ERROR"}`);return j}finally{clearTimeout(timer)}}
    try{
      const oltsResp=await get("/api/system/get_olts"),olts=arr(oltsResp),oltMap=new Map<string,string>();let ponCount=0;
      for(const o of olts){const pid=String(val(o,"id","olt_id","unique_id")||"");if(!pid)continue;const row={organization_id:oid,provider_id:pid,name:txt(val(o,"name","olt_name"),120)||`OLT ${pid}`,vendor:txt(val(o,"vendor"),80),model:txt(val(o,"olt_hardware_version","hardware_version","model"),120),provider_code:txt(val(o,"ip","code"),120),status:oltStatus(val(o,"status","operational_status")),last_seen_at:new Date().toISOString(),metadata:{ip:val(o,"ip"),telnet_port:val(o,"telnet_port"),snmp_port:val(o,"snmp_port"),info_updated:val(o,"info_updated")}};const{data,error}=await db.from("olt_devices").upsert(row,{onConflict:"organization_id,provider_id"}).select("id").single();if(error)throw error;oltMap.set(pid,data.id)}
      // PON: una llamada por OLT, no por ONU.
      for(const o of olts){const providerId=String(val(o,"id","olt_id","unique_id")||""),localOlt=oltMap.get(providerId);if(!localOlt)continue;let pons:any[]=[];try{pons=arr(await get(`/api/system/get_olt_pon_ports_details/${encodeURIComponent(providerId)}`))}catch(e){console.warn("PON sync",providerId,e)}for(const p of pons){const slot=Number(val(p,"board","slot")||0),port=Number(val(p,"pon_port","port")||0);if(!port)continue;const row={organization_id:oid,olt_id:localOlt,frame:0,slot,port,label:txt(val(p,"description"),120)||`${slot}/${port}`,status:String(val(p,"operational_status","status")||"UNKNOWN").toUpperCase(),onu_count:Number(val(p,"onus_count","total_onus")||0),online_onu_count:Number(val(p,"online_onus_count","online_onus")||0),average_signal:num(val(p,"average_signal")),tx_power:num(val(p,"tx_power")),last_seen_at:new Date().toISOString()};const{error}=await db.from("olt_pons").upsert(row,{onConflict:"olt_id,frame,slot,port"});if(error)throw error;ponCount++}}
      // Endpoints masivos recomendados por SmartOLT; no hacer una consulta por cada ONU.
      const [detailsR,statusR,signalsR]=await Promise.allSettled([get("/api/onu/get_onus_details"),get("/api/onu/get_onus_statuses"),get("/api/onu/get_onus_signals")]);
      const details=detailsR.status==="fulfilled"?arr(detailsR.value):[],statuses=statusR.status==="fulfilled"?arr(statusR.value):[],signals=signalsR.status==="fulfilled"?arr(signalsR.value):[];
      const sm=new Map<string,any>(),gm=new Map<string,any>();for(const x of statuses){const k=keyFor(x);if(k)sm.set(k,x)}for(const x of signals){const k=keyFor(x);if(k)gm.set(k,x)}
      const source=details.length?details:[...statuses,...signals],seen=new Set<string>();let onuCount=0;
      for(const d of source){const k=keyFor(d);if(!k||seen.has(k))continue;seen.add(k);const st=sm.get(k)||{},sg=gm.get(k)||{};const serial=txt(val(d,"serial_number","sn","serial","onu_sn"),100)||txt(val(st,"serial_number","sn","serial"),100)||txt(val(sg,"serial_number","sn","serial"),100)||k;const oltProvider=String(val(d,"olt_id","olt_unique_id")||val(st,"olt_id")||val(sg,"olt_id")||"");const oltId=oltMap.get(oltProvider)||null;const slot=Number(val(d,"board","slot")||val(st,"board","slot")||0),port=Number(val(d,"port","pon_port")||val(st,"port","pon_port")||0);let ponId:string|null=null;if(oltId&&port){const{data:p}=await db.from("olt_pons").select("id").eq("olt_id",oltId).eq("frame",0).eq("slot",slot).eq("port",port).maybeSingle();ponId=p?.id||null}const row:any={organization_id:oid,provider_external_id:txt(val(d,"unique_external_id","onu_external_id","id","external_id"),120)||k,olt_id:oltId,pon_id:ponId,name:txt(val(d,"name","onu_name","customer_name"),180),serial_number:serial,onu_id:txt(val(d,"onu_id","onu_number"),80),olt_name:txt(val(d,"olt_name"),120),pon_label:txt(val(d,"pon","pon_label"),100)||((slot||port)?`${slot}/${port}`:null),status:statusMap(val(st,"status","onu_status")||val(d,"status","onu_status")),rx_dbm:num(val(sg,"signal","rx_power","rx_signal","onu_rx_signal")||val(d,"signal","rx_power")),tx_dbm:num(val(sg,"tx_power","tx_signal","onu_tx_signal")||val(d,"tx_power")),distance_m:num(val(d,"distance","distance_m")),last_seen_at:new Date().toISOString(),metadata:{zone:val(d,"zone","zone_name"),odb:val(d,"odb","odb_name"),raw_provider_id:k}};const{error}=await db.from("olt_onus").upsert(row,{onConflict:"organization_id,serial_number"});if(error)throw error;onuCount++}
      await db.from("integration_connections").update({status:"ACTIVE",last_sync_at:new Date().toISOString(),last_error:null}).eq("id",conn.id);
      return json({ok:true,olts:oltMap.size,pons:ponCount,onus:onuCount});
    }catch(e){const message=e instanceof Error?e.message:"SMARTOLT_SYNC_ERROR";await db.from("integration_connections").update({status:"ERROR",last_error:message.slice(0,500)}).eq("id",conn.id);throw new HttpError(502,"SMARTOLT_SYNC_FAILED")}
  }catch(e){return handleError(e)}
});
