import {
  adminClient, audit, cleanText, encryptSecret, handleError, HttpError, json,
  normalizePhone, options, parseJson, randomReadable, requireCustomer,
  requireOrgAccess, requirePlatformAdmin, requireUser, sha256, validUuid,
} from "../_shared/core.ts";

const STAFF_ROLES = ["OWNER","ADMIN","BILLING","SUPPORT","TECHNICIAN"];
const ADMIN_ROLES = ["OWNER","ADMIN"];
const BILLING_ROLES = ["OWNER","ADMIN","BILLING"];
const TECH_ROLES = ["OWNER","ADMIN","TECHNICIAN"];
const TERMINAL_ALIASES = new Set(["system_resource","interfaces","ip_addresses","routes","ppp_active","dhcp_leases","hotspot_active","ping_gateway"]);
const ACCESS_TYPES = new Set(["PPPOE","DHCP","STATIC","HOTSPOT"]);
const CHANNEL_TYPES = new Set(["YAPE","PLIN","BANK_TRANSFER","CASH","PAYMENT_LINK"]);

function required(v: unknown, name: string, max=180) {
  const s=cleanText(v,max); if(!s) throw new HttpError(400,`${name}_REQUIRED`); return s;
}
function numberIn(v:unknown,min:number,max:number,name:string){const n=Number(v);if(!Number.isFinite(n)||n<min||n>max)throw new HttpError(400,`${name}_INVALID`);return n}
function bool(v:unknown){return v===true||v==="true"||v===1||v==="1"}
function orgId(body:Record<string,any>){if(!validUuid(body.organization_id))throw new HttpError(400,"ORGANIZATION_ID_INVALID");return body.organization_id}
function uuid(v:unknown,name:string){if(!validUuid(v))throw new HttpError(400,`${name}_INVALID`);return v}
function normalizeAccess(v:unknown){const s=cleanText(v,20).toUpperCase();if(!ACCESS_TYPES.has(s))throw new HttpError(400,"ACCESS_TYPE_INVALID");return s}
function sourceField(access:string,key:string){if(access==="PPPOE")return{pppoe_username:key};if(access==="DHCP")return{dhcp_mac:key.toUpperCase()};if(access==="STATIC")return{static_ip:key};return{hotspot_username:key}}
function rateLimit(plan:any){return `${Number(plan.upload_mbps)}M/${Number(plan.download_mbps)}M`}
function nowId(prefix:string){return `${prefix}:${crypto.randomUUID()}`}
async function mustGet(db:any,table:string,id:string,columns="*"){const{data,error}=await db.from(table).select(columns).eq("id",id).maybeSingle();if(error)throw error;if(!data)throw new HttpError(404,`${table.toUpperCase()}_NOT_FOUND`);return data}
async function orgObject(db:any,id:string){const{data}=await db.from("organizations").select("id,name,slug,status,support_phone,timezone").eq("id",id).maybeSingle();return data||null}

async function whoami(req:Request,db:any,user:any){
  const [{data:pa},{data:members},{data:cu}] = await Promise.all([
    db.from("platform_admins").select("role,active").eq("user_id",user.id).eq("active",true).maybeSingle(),
    db.from("organization_members").select("organization_id,role,organizations(id,name,slug,status,support_phone,timezone)").eq("user_id",user.id).eq("active",true),
    db.from("customer_users").select("customer_id,customers!inner(id,organization_id,full_name,nickname,phone,status,organizations!inner(id,name,slug,status,support_phone,timezone,organization_settings(customer_portal_enabled)))").eq("user_id",user.id).eq("active",true),
  ]);
  const activeMembers=(members||[]).filter((m:any)=>{const o=Array.isArray(m.organizations)?m.organizations[0]:m.organizations;return o&&["TRIAL","ACTIVE"].includes(String(o.status))});
  const activeCustomers=(cu||[]).filter((x:any)=>{const c=Array.isArray(x.customers)?x.customers[0]:x.customers;const o=Array.isArray(c?.organizations)?c.organizations[0]:c?.organizations;const stRaw=o?.organization_settings;const st=Array.isArray(stRaw)?stRaw[0]:stRaw;return c?.status==="ACTIVE"&&o&&["TRIAL","ACTIVE"].includes(String(o.status))&&st?.customer_portal_enabled!==false});
  const portals:string[]=[]; if(pa)portals.push("admin"); if(activeMembers.length)portals.push("isp"); if(activeCustomers.length)portals.push("customer");
  if(!portals.length) throw new HttpError(403,"ACCOUNT_WITHOUT_PORTAL");
  const member=activeMembers[0]||null; const customerLink=activeCustomers[0]||null;
  const customer:any=customerLink ? (Array.isArray(customerLink.customers)?customerLink.customers[0]:customerLink.customers) : null;
  const org:any=member ? (Array.isArray(member.organizations)?member.organizations[0]:member.organizations) : customer?.organizations||null;
  return json({ok:true,portals,role:pa?.role||member?.role||"CUSTOMER",organization_id:member?.organization_id||customer?.organization_id||null,organization:org,customer_id:customerLink?.customer_id||null,customer,display_name:user.user_metadata?.display_name||customer?.nickname||customer?.full_name||user.email||user.phone||"Usuario",email:user.email||null,phone:user.phone||null,must_change_password:!!user.user_metadata?.must_change_password});
}

async function platformCreateOrganization(db:any,user:any,body:any){
  await requirePlatformAdmin(db,user.id);
  const name=required(body.name,"NAME",100),slug=required(body.slug,"SLUG",60).toLowerCase().replace(/[^a-z0-9-]/g,"-").replace(/-+/g,"-").replace(/^-|-$/g,"");
  if(slug.length<3)throw new HttpError(400,"SLUG_INVALID");
  const email=required(body.owner_email,"OWNER_EMAIL",200).toLowerCase(); if(!/^\S+@\S+\.\S+$/.test(email))throw new HttpError(400,"OWNER_EMAIL_INVALID");
  const password=String(body.owner_password||"");if(password.length<10)throw new HttpError(400,"OWNER_PASSWORD_TOO_SHORT");
  const{data:org,error:oe}=await db.from("organizations").insert({name,slug,support_phone:cleanText(body.support_phone,40)||null,status:"TRIAL"}).select().single();if(oe)throw oe;
  let createdUser:any=null;
  try{
    const{data:au,error:ae}=await db.auth.admin.createUser({email,password,email_confirm:true,user_metadata:{display_name:name,must_change_password:true,portal:"isp"}});if(ae||!au.user)throw new HttpError(409,"OWNER_AUTH_CREATE_FAILED");createdUser=au.user;
    const{error:me}=await db.from("organization_members").insert({organization_id:org.id,user_id:createdUser.id,role:"OWNER"});if(me)throw me;
  }catch(e){if(createdUser?.id)await db.auth.admin.deleteUser(createdUser.id).catch(()=>{});await db.from("organizations").delete().eq("id",org.id);throw e}
  await audit(db,org.id,user.id,"ORGANIZATION_CREATED","organization",org.id,{name,slug});
  return json({ok:true,data:org});
}
async function platformSetOrganizationStatus(db:any,user:any,body:any){await requirePlatformAdmin(db,user.id);const id=uuid(body.organization_id,"ORGANIZATION_ID");const status=required(body.status,"STATUS",20).toUpperCase();if(!["TRIAL","ACTIVE","PAUSED","CANCELLED"].includes(status))throw new HttpError(400,"STATUS_INVALID");const{data,error}=await db.from("organizations").update({status}).eq("id",id).select().single();if(error)throw error;await audit(db,id,user.id,"ORGANIZATION_STATUS_CHANGED","organization",id,{status});return json({ok:true,data})}

async function ensureCustomerAuth(db:any,customerId:string,phone:string,name:string){
  const{data:existing}=await db.from("customer_users").select("user_id").eq("customer_id",customerId).eq("active",true).maybeSingle();if(existing)return existing.user_id;
  const{data,error}=await db.auth.admin.createUser({phone,phone_confirm:true,user_metadata:{display_name:name,portal:"customer"}});
  if(error||!data.user){console.error("customer auth create",error);throw new HttpError(409,"CUSTOMER_PHONE_ALREADY_REGISTERED_OR_INVALID")}
  const{error:le}=await db.from("customer_users").insert({customer_id:customerId,user_id:data.user.id});if(le){await db.auth.admin.deleteUser(data.user.id).catch(()=>{});throw le}
  return data.user.id;
}
async function queueAccessCommand(db:any,userId:string,service:any,plan:any,type:string,extra:any={}){
  if(!service.router_id)throw new HttpError(400,"SERVICE_WITHOUT_ROUTER");const source=service.router_source_key||service.pppoe_username||service.dhcp_mac||service.static_ip||service.hotspot_username;
  const payload={access_type:service.access_type,source_key:String(source||""),router_profile:plan?.router_profile||null,rate_limit:plan?rateLimit(plan):null,...extra};
  const{data,error}=await db.from("network_commands").insert({organization_id:service.organization_id,router_id:service.router_id,service_id:service.id,customer_id:service.customer_id,command_type:type,payload,idempotency_key:nowId(type.toLowerCase()),created_by:userId}).select("id").single();if(error)throw error;return data.id;
}
async function createCustomerService(db:any,user:any,body:any){
  const oid=orgId(body);await requireOrgAccess(db,user.id,oid,STAFF_ROLES);const c=body.customer||{},s=body.service||{};const phone=normalizePhone(c.phone),full_name=required(c.full_name,"FULL_NAME",140),access=normalizeAccess(s.access_type),key=required(s.source_key,"SOURCE_KEY",120),planId=uuid(s.plan_id,"PLAN_ID"),routerId=uuid(s.router_id,"ROUTER_ID");
  const [plan,router]=await Promise.all([mustGet(db,"plans",planId),mustGet(db,"routers",routerId)]);if(plan.organization_id!==oid||router.organization_id!==oid)throw new HttpError(403,"CROSS_ORG_REFERENCE");if(!plan.active)throw new HttpError(400,"PLAN_INACTIVE");if(!(plan.supported_access||[]).includes(access))throw new HttpError(400,"PLAN_ACCESS_NOT_SUPPORTED");
  let customer:any=null,service:any=null,authUserId:string|null=null;
  try{
    const{data:cd,error:ce}=await db.from("customers").insert({organization_id:oid,full_name,nickname:cleanText(c.nickname,80)||null,phone,whatsapp:c.whatsapp?normalizePhone(c.whatsapp):phone,document_number:cleanText(c.document_number,30)||null,address:cleanText(c.address,240)||null}).select().single();if(ce)throw ce;customer=cd;
    authUserId=await ensureCustomerAuth(db,customer.id,phone,full_name);
    const sf=sourceField(access,key);const insert:any={organization_id:oid,customer_id:customer.id,plan_id:planId,router_id:routerId,access_type:access,status:"PENDING",router_source_key:key,...sf};
    const{data:sv,error:se}=await db.from("services").insert(insert).select().single();if(se)throw se;service=sv;
    let accessSecret:string|null=null;
    if(access==="PPPOE"){
      accessSecret=randomReadable(16);const enc=await encryptSecret(accessSecret);await db.from("service_credentials").insert({service_id:service.id,organization_id:oid,username:key,secret_ciphertext:enc.ciphertext,secret_iv:enc.iv});
    }
    const cmdPayload:any={access_type:access,source_key:key,router_profile:plan.router_profile,rate_limit:rateLimit(plan),access_secret:accessSecret};
    const{data:cmd,error:qe}=await db.from("network_commands").insert({organization_id:oid,router_id:routerId,service_id:service.id,customer_id:customer.id,command_type:"CREATE_ACCESS",payload:cmdPayload,idempotency_key:nowId("create"),created_by:user.id}).select("id").single();if(qe)throw qe;
    await audit(db,oid,user.id,"CUSTOMER_SERVICE_CREATED","service",service.id,{customer_id:customer.id,access_type:access,plan_id:planId,router_id:routerId});
    return json({ok:true,customer_id:customer.id,service_id:service.id,command_id:cmd.id,access_username:key,access_secret:accessSecret});
  }catch(e){if(service?.id)await db.from("services").delete().eq("id",service.id);if(customer?.id)await db.from("customers").delete().eq("id",customer.id);if(authUserId)await db.auth.admin.deleteUser(authUserId).catch(()=>{});throw e}
}
async function serviceAction(db:any,user:any,body:any){
  const oid=orgId(body);await requireOrgAccess(db,user.id,oid,STAFF_ROLES);const sid=uuid(body.service_id,"SERVICE_ID"),op=required(body.operation,"OPERATION",30).toUpperCase();if(!["ENABLE","SUSPEND","PLAN_CHANGE","REMOVE_ACCESS"].includes(op))throw new HttpError(400,"OPERATION_INVALID");const service=await mustGet(db,"services",sid);if(service.organization_id!==oid)throw new HttpError(403,"CROSS_ORG_REFERENCE");let plan:any=null,extra:any={};if(op==="PLAN_CHANGE"){const pid=uuid(body.plan_id,"PLAN_ID");plan=await mustGet(db,"plans",pid);if(plan.organization_id!==oid||!plan.active)throw new HttpError(400,"PLAN_INVALID");if(!(plan.supported_access||[]).includes(service.access_type))throw new HttpError(400,"PLAN_ACCESS_NOT_SUPPORTED");extra.to_plan_id=pid}else if(service.plan_id)plan=await mustGet(db,"plans",service.plan_id);
  const commandId=await queueAccessCommand(db,user.id,service,plan,op,extra);await audit(db,oid,user.id,"SERVICE_ACTION_QUEUED","service",sid,{operation:op,command_id:commandId,to_plan_id:extra.to_plan_id});return json({ok:true,command_id:commandId});
}
async function importObservation(db:any,user:any,body:any){
  const oid=orgId(body);await requireOrgAccess(db,user.id,oid,STAFF_ROLES);const observation=await mustGet(db,"router_observations",uuid(body.observation_id,"OBSERVATION_ID"));if(observation.organization_id!==oid||observation.state!=="UNMATCHED")throw new HttpError(400,"OBSERVATION_NOT_IMPORTABLE");const phone=normalizePhone(body.phone),full_name=required(body.full_name,"FULL_NAME",140);
  const{data:plans}=await db.from("plans").select("*").eq("organization_id",oid).eq("active",true);const plan=(plans||[]).find((p:any)=>String(p.router_profile||"").toLowerCase()===String(observation.router_profile||"").toLowerCase())||null;
  let customer:any=null,authId:string|null=null;try{const{data:c,error}=await db.from("customers").insert({organization_id:oid,full_name,phone,whatsapp:body.whatsapp?normalizePhone(body.whatsapp):phone}).select().single();if(error)throw error;customer=c;authId=await ensureCustomerAuth(db,c.id,phone,full_name);const sf=sourceField(observation.source_type,observation.source_key);const{data:s,error:se}=await db.from("services").insert({organization_id:oid,customer_id:c.id,plan_id:plan?.id||null,router_id:observation.router_id,access_type:observation.source_type,status:"ACTIVE",router_source_key:observation.source_key,...sf}).select().single();if(se)throw se;await db.from("router_observations").update({state:"MATCHED",customer_id:c.id}).eq("id",observation.id);await audit(db,oid,user.id,"ROUTER_OBSERVATION_IMPORTED","service",s.id,{observation_id:observation.id,plan_id:plan?.id||null});return json({ok:true,customer_id:c.id,service_id:s.id,matched_plan:plan?.name||null})}catch(e){if(customer?.id)await db.from("customers").delete().eq("id",customer.id);if(authId)await db.auth.admin.deleteUser(authId).catch(()=>{});throw e}
}
async function savePlan(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,ADMIN_ROLES);const p=body.plan||{};const row:any={organization_id:oid,name:required(p.name,"PLAN_NAME",100),code:required(p.code,"PLAN_CODE",50).toUpperCase(),router_profile:required(p.router_profile,"ROUTER_PROFILE",100),download_mbps:numberIn(p.download_mbps,1,100000,"DOWNLOAD"),upload_mbps:numberIn(p.upload_mbps,1,100000,"UPLOAD"),price:numberIn(p.price,0,100000,"PRICE"),supported_access:(Array.isArray(p.supported_access)?p.supported_access:[]).map((x:any)=>normalizeAccess(x)),active:p.active===undefined?true:bool(p.active)};if(!row.supported_access.length)throw new HttpError(400,"SUPPORTED_ACCESS_REQUIRED");let query;if(p.id){const id=uuid(p.id,"PLAN_ID");query=db.from("plans").update(row).eq("id",id).eq("organization_id",oid).select().single()}else query=db.from("plans").insert(row).select().single();const{data,error}=await query;if(error)throw error;await audit(db,oid,user.id,"PLAN_SAVED","plan",data.id,{name:data.name});return json({ok:true,data})}
async function saveNode(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,TECH_ROLES);const n=body.node||{};const row:any={organization_id:oid};for(const k of ["name","code","address","notes","status","node_type"])if(n[k]!==undefined)row[k]=cleanText(n[k],k==="notes"?1000:180)||null;if(n.latitude!==undefined)row.latitude=numberIn(n.latitude,-90,90,"LATITUDE");if(n.longitude!==undefined)row.longitude=numberIn(n.longitude,-180,180,"LONGITUDE");if(n.metadata&&typeof n.metadata==="object")row.metadata=n.metadata;if(!body.id){row.name=required(n.name,"NAME",120);row.node_type=required(n.node_type,"NODE_TYPE",20).toUpperCase();if(!["POP","OLT","NAP","SPLITTER","OTHER"].includes(row.node_type))throw new HttpError(400,"NODE_TYPE_INVALID")}const query=body.id?db.from("network_nodes").update(row).eq("id",uuid(body.id,"NODE_ID")).eq("organization_id",oid).select().single():db.from("network_nodes").insert(row).select().single();const{data,error}=await query;if(error)throw error;await audit(db,oid,user.id,"NETWORK_NODE_SAVED","network_node",data.id,{name:data.name,node_type:data.node_type});return json({ok:true,data})}
async function saveLink(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,TECH_ROLES);const l=body.link||{};const geometry=Array.isArray(l.geometry)?l.geometry.slice(0,1000).map((p:any)=>({lat:numberIn(p.lat,-90,90,"LATITUDE"),lng:numberIn(p.lng,-180,180,"LONGITUDE")})):[];if(geometry.length<2)throw new HttpError(400,"LINK_GEOMETRY_REQUIRED");const row:any={organization_id:oid,name:cleanText(l.name,120)||null,link_type:cleanText(l.link_type||"FIBER",20).toUpperCase(),fiber_count:numberIn(l.fiber_count||1,1,288,"FIBER_COUNT"),status:cleanText(l.status||"ACTIVE",20).toUpperCase(),geometry,from_node_id:validUuid(l.from_node_id)?l.from_node_id:null,to_node_id:validUuid(l.to_node_id)?l.to_node_id:null};const{data,error}=await db.from("network_links").insert(row).select().single();if(error)throw error;await audit(db,oid,user.id,"NETWORK_LINK_CREATED","network_link",data.id,{name:data.name});return json({ok:true,data})}

async function saveServiceLocation(db:any,user:any,body:any){
  const oid=orgId(body);await requireOrgAccess(db,user.id,oid,TECH_ROLES);const sid=uuid(body.service_id,"SERVICE_ID"),service=await mustGet(db,"services",sid);if(service.organization_id!==oid)throw new HttpError(403,"CROSS_ORG_REFERENCE");
  let parent:string|null=null;if(body.parent_node_id){parent=uuid(body.parent_node_id,"PARENT_NODE_ID");const node=await mustGet(db,"network_nodes",parent);if(node.organization_id!==oid)throw new HttpError(403,"CROSS_ORG_REFERENCE")}
  const row:any={service_id:sid,organization_id:oid,customer_id:service.customer_id,parent_node_id:parent,address:cleanText(body.address,240)||null,label:cleanText(body.label,80)||"Casa",source:"STAFF"};
  if(body.latitude!==null&&body.latitude!==undefined&&body.latitude!=="")row.latitude=numberIn(body.latitude,-90,90,"LATITUDE");
  if(body.longitude!==null&&body.longitude!==undefined&&body.longitude!=="")row.longitude=numberIn(body.longitude,-180,180,"LONGITUDE");
  const{data,error}=await db.from("service_locations").upsert(row,{onConflict:"service_id"}).select().single();if(error)throw error;
  if(row.address)await db.from("customers").update({address:row.address}).eq("id",service.customer_id);
  await audit(db,oid,user.id,"SERVICE_LOCATION_SAVED","service",sid,{parent_node_id:parent,latitude:row.latitude??null,longitude:row.longitude??null});return json({ok:true,data})
}
async function linkOnu(db:any,user:any,body:any){
  const oid=orgId(body);await requireOrgAccess(db,user.id,oid,TECH_ROLES);const onuId=uuid(body.onu_id,"ONU_ID"),sid=uuid(body.service_id,"SERVICE_ID");const[onu,service]=await Promise.all([mustGet(db,"olt_onus",onuId),mustGet(db,"services",sid)]);if(onu.organization_id!==oid||service.organization_id!==oid)throw new HttpError(403,"CROSS_ORG_REFERENCE");const{data,error}=await db.from("olt_onus").update({service_id:sid,customer_id:service.customer_id}).eq("id",onuId).select().single();if(error)throw error;await audit(db,oid,user.id,"ONU_LINKED","olt_onu",onuId,{service_id:sid,customer_id:service.customer_id});return json({ok:true,data})
}
async function reviewCustomerRequest(db:any,user:any,body:any){
  const oid=orgId(body);await requireOrgAccess(db,user.id,oid,STAFF_ROLES);const rid=uuid(body.request_id,"REQUEST_ID"),approve=bool(body.approve),request=await mustGet(db,"customer_requests",rid);if(request.organization_id!==oid||request.status!=="PENDING")throw new HttpError(400,"REQUEST_NOT_REVIEWABLE");
  if(!approve){const{data,error}=await db.from("customer_requests").update({status:"REJECTED",reviewed_at:new Date().toISOString(),reviewed_by:user.id}).eq("id",rid).select().single();if(error)throw error;return json({ok:true,data})}
  if(request.request_type!=="PLAN_CHANGE")throw new HttpError(400,"REQUEST_TYPE_NOT_AUTOMATABLE");const sid=request.service_id,planId=request.payload?.plan_id;if(!validUuid(sid)||!validUuid(planId))throw new HttpError(400,"REQUEST_PAYLOAD_INVALID");const[service,plan]=await Promise.all([mustGet(db,"services",sid),mustGet(db,"plans",planId)]);if(service.organization_id!==oid||plan.organization_id!==oid||!plan.active)throw new HttpError(400,"REQUEST_TARGET_INVALID");if(!(plan.supported_access||[]).includes(service.access_type))throw new HttpError(400,"PLAN_ACCESS_NOT_SUPPORTED");
  const commandId=await queueAccessCommand(db,user.id,service,plan,"PLAN_CHANGE",{to_plan_id:plan.id,request_id:rid});const{data,error}=await db.from("customer_requests").update({status:"APPROVED",reviewed_at:new Date().toISOString(),reviewed_by:user.id}).eq("id",rid).select().single();if(error)throw error;await audit(db,oid,user.id,"CUSTOMER_REQUEST_APPROVED","customer_request",rid,{command_id:commandId,plan_id:plan.id});return json({ok:true,data,command_id:commandId})
}
async function integrationStatus(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,STAFF_ROLES);const{data}=await db.from("integration_connections").select("provider,public_config,status,last_sync_at,last_error,updated_at").eq("organization_id",oid).eq("provider","SMARTOLT").maybeSingle();return json({ok:true,configured:!!data,status:data?.status||null,last_sync_at:data?.last_sync_at||null,last_error:data?.last_error||null,subdomain:data?.public_config?.subdomain||null})}
async function configureSmartOLT(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,ADMIN_ROLES);const subdomain=required(body.subdomain,"SUBDOMAIN",100).toLowerCase().replace(/\.smartolt\.com$/i,"");if(!/^[a-z0-9][a-z0-9-]{1,98}[a-z0-9]$/.test(subdomain))throw new HttpError(400,"SMARTOLT_SUBDOMAIN_INVALID");const apiKey=required(body.api_key,"API_KEY",500);const enc=await encryptSecret(apiKey);const{data,error}=await db.from("integration_connections").upsert({organization_id:oid,provider:"SMARTOLT",public_config:{subdomain},secret_ciphertext:enc.ciphertext,secret_iv:enc.iv,status:"CONFIGURED",last_error:null},{onConflict:"organization_id,provider"}).select("id,status,public_config").single();if(error)throw error;await audit(db,oid,user.id,"SMARTOLT_CONFIGURED","integration",data.id,{subdomain});return json({ok:true,data:{id:data.id,status:data.status,subdomain}})}
async function hotspotBatch(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,TECH_ROLES);const rid=uuid(body.router_id,"ROUTER_ID"),router=await mustGet(db,"routers",rid);if(router.organization_id!==oid)throw new HttpError(403,"CROSS_ORG_REFERENCE");const qty=numberIn(body.quantity,1,100,"QUANTITY"),name=required(body.name,"NAME",100),profile=required(body.profile_name,"PROFILE_NAME",100),duration=body.duration_minutes?numberIn(body.duration_minutes,1,525600,"DURATION"):null,price=Number(body.price||0);const{data:batch,error:be}=await db.from("hotspot_batches").insert({organization_id:oid,router_id:rid,name,quantity:qty,profile_name:profile,duration_minutes:duration,price,created_by:user.id}).select().single();if(be)throw be;const out:any[]=[];try{for(let i=0;i<qty;i++){const username=`R${randomReadable(8).toUpperCase()}`,secret=randomReadable(10),enc=await encryptSecret(secret),hash=await sha256(secret);const{data:v,error:ve}=await db.from("hotspot_vouchers").insert({organization_id:oid,batch_id:batch.id,username,secret_hash:hash,secret_ciphertext:enc.ciphertext,secret_iv:enc.iv}).select("id,username").single();if(ve)throw ve;const{error:ce}=await db.from("network_commands").insert({organization_id:oid,router_id:rid,command_type:"CREATE_ACCESS",payload:{access_type:"HOTSPOT",source_key:username,access_secret:secret,router_profile:profile,duration_minutes:duration,voucher_id:v.id},idempotency_key:`voucher:${v.id}`,created_by:user.id});if(ce)throw ce;out.push({id:v.id,username,password:secret,duration_minutes:duration,price})}await db.from("hotspot_batches").update({status:"READY"}).eq("id",batch.id);await audit(db,oid,user.id,"HOTSPOT_BATCH_GENERATED","hotspot_batch",batch.id,{quantity:qty,profile});return json({ok:true,batch_id:batch.id,vouchers:out})}catch(e){await db.from("hotspot_batches").update({status:"CANCELLED"}).eq("id",batch.id);throw e}}
async function reviewPayment(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,BILLING_ROLES);const report=await mustGet(db,"payment_reports",uuid(body.report_id,"REPORT_ID"));if(report.organization_id!==oid)throw new HttpError(403,"CROSS_ORG_REFERENCE");const{data,error}=await db.rpc("review_customer_payment_report",{p_report_id:report.id,p_reviewer:user.id,p_approve:bool(body.approve),p_note:cleanText(body.note,240)||null});if(error)throw error;await audit(db,oid,user.id,bool(body.approve)?"PAYMENT_APPROVED":"PAYMENT_REJECTED","payment_report",report.id,{note:cleanText(body.note,240)||null});return json({ok:true,data})}
async function generateInvoices(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,BILLING_ROLES);const{data,error}=await db.rpc("generate_due_invoices",{p_org:oid});if(error)throw error;return json({ok:true,generated:Number(data||0)})}
async function savePaymentChannel(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,BILLING_ROLES);const c=body.channel||{};const type=required(c.type,"TYPE",30).toUpperCase();if(!CHANNEL_TYPES.has(type))throw new HttpError(400,"CHANNEL_TYPE_INVALID");const row:any={organization_id:oid,type,display_name:required(c.display_name,"DISPLAY_NAME",100),receiver_name:required(c.receiver_name,"RECEIVER_NAME",120),account_reference:cleanText(c.account_reference,120)||null,instructions:cleanText(c.instructions,600)||null,active:c.active===undefined?true:bool(c.active)};const query=c.id?db.from("payment_channels").update(row).eq("id",uuid(c.id,"CHANNEL_ID")).eq("organization_id",oid).select().single():db.from("payment_channels").insert(row).select().single();const{data,error}=await query;if(error)throw error;return json({ok:true,data})}
async function setPaymentQr(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,BILLING_ROLES);const cid=uuid(body.channel_id,"CHANNEL_ID"),path=required(body.object_path,"OBJECT_PATH",300);if(!path.startsWith(`${oid}/`))throw new HttpError(400,"QR_PATH_INVALID");const{data,error}=await db.from("payment_channels").update({qr_object_path:path}).eq("id",cid).eq("organization_id",oid).select("id,qr_object_path").single();if(error)throw error;return json({ok:true,data})}
async function replyTicket(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,["OWNER","ADMIN","SUPPORT","TECHNICIAN"]);const tid=uuid(body.ticket_id,"TICKET_ID"),ticket=await mustGet(db,"support_tickets",tid);if(ticket.organization_id!==oid)throw new HttpError(403,"CROSS_ORG_REFERENCE");const text=required(body.body,"BODY",4000);const{data,error}=await db.from("support_messages").insert({ticket_id:tid,organization_id:oid,sender_user_id:user.id,sender_type:"STAFF",body:text}).select().single();if(error)throw error;let next=cleanText(body.status,30).toUpperCase();if(!["OPEN","IN_PROGRESS","RESOLVED","CLOSED"].includes(next))next=ticket.status==="OPEN"?"IN_PROGRESS":ticket.status;await db.from("support_tickets").update({status:next}).eq("id",tid);return json({ok:true,data,status:next})}
async function routerAction(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,TECH_ROLES);const rid=uuid(body.router_id,"ROUTER_ID"),router=await mustGet(db,"routers",rid);if(router.organization_id!==oid)throw new HttpError(403,"CROSS_ORG_REFERENCE");const action=required(body.operation||body.action,"OPERATION",30).toUpperCase();if(action!=="INVENTORY_NOW")throw new HttpError(400,"ROUTER_ACTION_NOT_ALLOWED");const{data,error}=await db.from("network_commands").insert({organization_id:oid,router_id:rid,command_type:"INVENTORY_NOW",payload:{},idempotency_key:nowId("inventory"),created_by:user.id}).select("id").single();if(error)throw error;return json({ok:true,command_id:data.id})}
async function routerTerminal(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,TECH_ROLES);const rid=uuid(body.router_id,"ROUTER_ID"),router=await mustGet(db,"routers",rid);if(router.organization_id!==oid)throw new HttpError(403,"CROSS_ORG_REFERENCE");const alias=required(body.terminal_alias,"TERMINAL_ALIAS",50);if(!TERMINAL_ALIASES.has(alias))throw new HttpError(400,"TERMINAL_ALIAS_NOT_ALLOWED");const{data,error}=await db.from("network_commands").insert({organization_id:oid,router_id:rid,command_type:"TERMINAL_READ",payload:{terminal_alias:alias},idempotency_key:nowId("terminal"),created_by:user.id}).select("id").single();if(error)throw error;await audit(db,oid,user.id,"ROUTER_DIAGNOSTIC_QUEUED","router",rid,{alias,command_id:data.id});return json({ok:true,command_id:data.id})}
async function saveSettings(db:any,user:any,body:any){const oid=orgId(body);await requireOrgAccess(db,user.id,oid,ADMIN_ROLES);const s=body.settings||body;const row:any={organization_id:oid};if(s.grace_days!==undefined)row.grace_days=numberIn(s.grace_days,0,31,"GRACE_DAYS");if(s.due_day!==undefined)row.due_day=numberIn(s.due_day,1,28,"DUE_DAY");if(s.auto_suspend!==undefined)row.auto_suspend=bool(s.auto_suspend);if(s.customer_portal_enabled!==undefined)row.customer_portal_enabled=bool(s.customer_portal_enabled);const{data,error}=await db.from("organization_settings").upsert(row,{onConflict:"organization_id"}).select().single();if(error)throw error;await audit(db,oid,user.id,"ORGANIZATION_SETTINGS_UPDATED","organization_settings",oid,data);return json({ok:true,data})}

async function customerPlanChange(db:any,user:any,body:any){const ctx=await requireCustomer(db,user.id),sid=uuid(body.service_id,"SERVICE_ID"),pid=uuid(body.plan_id,"PLAN_ID");const service=await mustGet(db,"services",sid);if(service.customer_id!==ctx.customer_id)throw new HttpError(403,"CUSTOMER_ACCESS_DENIED");const plan=await mustGet(db,"plans",pid);if(plan.organization_id!==ctx.organization_id||!plan.active||!(plan.supported_access||[]).includes(service.access_type))throw new HttpError(400,"PLAN_INVALID");const{data,error}=await db.from("customer_requests").insert({organization_id:ctx.organization_id,customer_id:ctx.customer_id,service_id:sid,request_type:"PLAN_CHANGE",payload:{plan_id:pid,plan_name:plan.name}}).select().single();if(error)throw error;return json({ok:true,data})}
async function customerCreateTicket(db:any,user:any,body:any){const ctx=await requireCustomer(db,user.id);const sid=body.service_id?uuid(body.service_id,"SERVICE_ID"):null;if(sid){const s=await mustGet(db,"services",sid);if(s.customer_id!==ctx.customer_id)throw new HttpError(403,"CUSTOMER_ACCESS_DENIED")}const priority=required(body.priority||"NORMAL","PRIORITY",20).toUpperCase();if(!["LOW","NORMAL","HIGH","CRITICAL"].includes(priority))throw new HttpError(400,"PRIORITY_INVALID");const{data,error}=await db.from("support_tickets").insert({organization_id:ctx.organization_id,customer_id:ctx.customer_id,service_id:sid,subject:required(body.subject,"SUBJECT",180),detail:required(body.detail,"DETAIL",4000),priority}).select().single();if(error)throw error;await db.from("support_messages").insert({ticket_id:data.id,organization_id:ctx.organization_id,sender_user_id:user.id,sender_type:"CUSTOMER",body:data.detail});return json({ok:true,data})}
async function customerUpdateProfile(db:any,user:any,body:any){const ctx=await requireCustomer(db,user.id);const row:any={};if(body.nickname!==undefined)row.nickname=cleanText(body.nickname,80)||null;if(body.email!==undefined){const e=cleanText(body.email,200).toLowerCase();if(e&&!/^\S+@\S+\.\S+$/.test(e))throw new HttpError(400,"EMAIL_INVALID");row.email=e||null}if(body.whatsapp!==undefined)row.whatsapp=body.whatsapp?normalizePhone(body.whatsapp):null;if(!Object.keys(row).length)throw new HttpError(400,"NOTHING_TO_UPDATE");const{data,error}=await db.from("customers").update(row).eq("id",ctx.customer_id).select().single();if(error)throw error;await audit(db,ctx.organization_id,user.id,"CUSTOMER_PROFILE_UPDATED","customer",ctx.customer_id,{nickname:data.nickname,email:data.email,whatsapp:data.whatsapp});return json({ok:true,data})}
async function customerLocation(db:any,user:any,body:any){const ctx=await requireCustomer(db,user.id),sid=uuid(body.service_id,"SERVICE_ID"),service=await mustGet(db,"services",sid);if(service.customer_id!==ctx.customer_id)throw new HttpError(403,"CUSTOMER_ACCESS_DENIED");const row:any={service_id:sid,organization_id:ctx.organization_id,customer_id:ctx.customer_id,address:cleanText(body.address,240)||null,source:"CUSTOMER"};if(body.latitude!==null&&body.latitude!==undefined)row.latitude=numberIn(body.latitude,-90,90,"LATITUDE");if(body.longitude!==null&&body.longitude!==undefined)row.longitude=numberIn(body.longitude,-180,180,"LONGITUDE");const{data,error}=await db.from("service_locations").upsert(row,{onConflict:"service_id"}).select().single();if(error)throw error;if(body.reference!==undefined)await db.from("customers").update({address_reference:cleanText(body.reference,240)||null,address:row.address}).eq("id",ctx.customer_id);await audit(db,ctx.organization_id,user.id,"CUSTOMER_LOCATION_UPDATED","service",sid,{latitude:row.latitude||null,longitude:row.longitude||null});return json({ok:true,data})}
async function customerReportPayment(db:any,user:any,body:any){const ctx=await requireCustomer(db,user.id),iid=uuid(body.invoice_id,"INVOICE_ID"),cid=uuid(body.channel_id,"CHANNEL_ID");const [invoice,channel]=await Promise.all([mustGet(db,"invoices",iid),mustGet(db,"payment_channels",cid)]);if(invoice.customer_id!==ctx.customer_id||channel.organization_id!==ctx.organization_id||!channel.active)throw new HttpError(403,"PAYMENT_REFERENCE_INVALID");if(["PAID","VOID"].includes(invoice.status)||Number(invoice.balance)<=0)throw new HttpError(400,"INVOICE_NOT_PAYABLE");const amount=numberIn(body.amount,0.01,Number(invoice.balance),"AMOUNT"),path=required(body.proof_object_path,"PROOF_PATH",300);if(!path.startsWith(`${ctx.customer_id}/`))throw new HttpError(400,"PROOF_PATH_INVALID");const{data,error}=await db.from("payment_reports").insert({organization_id:ctx.organization_id,customer_id:ctx.customer_id,service_id:invoice.service_id,invoice_id:iid,channel_id:cid,amount,operation_reference:required(body.operation_reference,"OPERATION_REFERENCE",100),proof_object_path:path}).select().single();if(error)throw error;await audit(db,ctx.organization_id,user.id,"PAYMENT_REPORTED","payment_report",data.id,{invoice_id:iid,amount});return json({ok:true,data})}
async function customerReplyTicket(db:any,user:any,body:any){const ctx=await requireCustomer(db,user.id),tid=uuid(body.ticket_id,"TICKET_ID"),t=await mustGet(db,"support_tickets",tid);if(t.customer_id!==ctx.customer_id||t.status==="CLOSED")throw new HttpError(403,"TICKET_NOT_WRITABLE");const{data,error}=await db.from("support_messages").insert({ticket_id:tid,organization_id:ctx.organization_id,sender_user_id:user.id,sender_type:"CUSTOMER",body:required(body.body,"BODY",4000)}).select().single();if(error)throw error;return json({ok:true,data})}

Deno.serve(async(req:Request)=>{
  const pre=options(req);if(pre)return pre;if(req.method!=="POST")return json({ok:false,error:"METHOD_NOT_ALLOWED"},405);
  try{
    const db=adminClient(),user=await requireUser(req,db),body=await parseJson(req),action=required(body.action,"ACTION",80);
    switch(action){
      case"whoami":return whoami(req,db,user);
      case"platform_create_organization":return platformCreateOrganization(db,user,body);
      case"platform_set_organization_status":return platformSetOrganizationStatus(db,user,body);
      case"isp_create_customer_service":return createCustomerService(db,user,body);
      case"isp_service_action":return serviceAction(db,user,body);
      case"isp_import_observation":return importObservation(db,user,body);
      case"isp_save_plan":return savePlan(db,user,body);
      case"isp_save_network_node":return saveNode(db,user,body);
      case"isp_save_network_link":return saveLink(db,user,body);
      case"isp_save_service_location":return saveServiceLocation(db,user,body);
      case"isp_link_onu":return linkOnu(db,user,body);
      case"isp_integration_status":return integrationStatus(db,user,body);
      case"isp_configure_smartolt":return configureSmartOLT(db,user,body);
      case"isp_generate_hotspot_batch":return hotspotBatch(db,user,body);
      case"isp_review_payment":return reviewPayment(db,user,body);
      case"isp_generate_invoices":return generateInvoices(db,user,body);
      case"isp_save_payment_channel":return savePaymentChannel(db,user,body);
      case"isp_set_payment_qr":return setPaymentQr(db,user,body);
      case"isp_reply_ticket":return replyTicket(db,user,body);
      case"isp_review_customer_request":return reviewCustomerRequest(db,user,body);
      case"isp_router_action":return routerAction(db,user,body);
      case"isp_router_terminal":return routerTerminal(db,user,body);
      case"isp_save_settings":return saveSettings(db,user,body);
      case"customer_request_plan_change":return customerPlanChange(db,user,body);
      case"customer_create_ticket":return customerCreateTicket(db,user,body);
      case"customer_update_profile":return customerUpdateProfile(db,user,body);
      case"customer_update_location":return customerLocation(db,user,body);
      case"customer_report_payment":return customerReportPayment(db,user,body);
      case"customer_reply_ticket":return customerReplyTicket(db,user,body);
      default:throw new HttpError(404,"ACTION_NOT_FOUND");
    }
  }catch(e){return handleError(e)}
});
